import {test,expect} from '@playwright/test';
import {createTestCharacter} from '../uiHelpers';
test('GM tuning, weapon radar, shared Arts, and clean NPC quests',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?webgl');await createTestCharacter(page);
 await page.locator('#open-gm').click();await page.locator('#gm-enabled').check();await page.locator('#gm-item').selectOption('weapons.rapier');await page.locator('[data-path="damage"]').fill('18');await page.getByRole('button',{name:'Apply & save locally',exact:true}).click();await expect(page.locator('#gm-status')).toContainText('Applied');await page.screenshot({path:'test-results/gm-editor.png'});
 await page.reload();await expect(page.locator('#begin')).toBeEnabled({timeout:45000});await page.locator('#begin').click();await expect(page.locator('#guild-invitation')).toBeHidden();await page.keyboard.press('m');await page.locator('#friends-menu').click();await expect(page.locator('#personal-detail')).toContainText('Warden Ilyra');await expect(page.locator('#personal-guild')).toHaveCount(0);await expect(page.locator('.player-name')).not.toContainText('WAYFARER');await page.keyboard.press('m');
 await page.evaluate(()=>{const s=window.trinity.sim;s.player.x=-8;s.player.z=7;});await page.keyboard.press('e');await expect(page.locator('.rack-choice svg')).toHaveCount(3);await expect(page.locator('[data-weapon="rapier"]')).toContainText('18 base');const axis=page.locator('[data-weapon="sword"] .stat-radar g[data-help]').filter({hasText:'Break'});await axis.hover();await expect(page.locator('#context-help')).toBeVisible();await expect(page.locator('#context-help')).toContainText('Filling enemy Break staggers it');await axis.focus();await expect(page.locator('#context-help')).toBeVisible();await page.screenshot({path:'test-results/weapon-radars.png'});await page.keyboard.press('Escape');await expect(page.locator('#context-help')).toBeHidden();
 await page.locator('[data-weapon="sword"] summary').click();await expect(page.locator('[data-weapon="sword"]')).toContainText('6 per target');await page.locator('[data-take-weapon="rapier"]').click();await page.locator('#rack-close').click();expect(await page.evaluate(()=>window.trinity.sim.weaponDefinition.damage)).toBe(18);expect(await page.evaluate(()=>window.trinity.sim.progression.learned['focused-strike'])).toBe('starter');
 await page.keyboard.press('m');await page.locator('#character-menu').click();await page.locator('[data-category="arts"]').click();await page.locator('[data-skill="focused-strike"]').click();await page.locator('#loadout-tray .stat-radar summary').click();await expect(page.locator('#loadout-tray')).toContainText('filling Break staggers');await expect(page.locator('#loadout-tray')).toContainText('Basic Art');await page.screenshot({path:'test-results/skill-radar-guide.png'});await page.locator('#tray-close').click();
 await page.locator('#menu').click();await page.locator('#open-gm').click();await page.locator('#gm-enabled').uncheck();expect(await page.evaluate(()=>window.trinity.sim.weaponDefinition.damage)).toBe(10);await page.locator('#gm-close').click();await page.locator('#begin').click();await page.evaluate(()=>{const s=window.trinity.sim;s.player.x=2;s.player.z=-8;});await page.keyboard.press('e');await expect(page.locator('#orb-trials')).toHaveCount(0);await expect(page.locator('#orb-guided')).toContainText('Guild Combat Trial');expect(errors).toEqual([]);
});
