import {test,expect} from '@playwright/test';
async function opening(page:any,accept=true){await page.goto('/?webgl');await page.locator('#creation-name').fill('Aster');await page.locator('[name=character][value=woman]').check();await page.locator('#creation-weapon').selectOption('rapier');await page.locator('#character-creation button').click();await expect(page.locator('#dialogue-next')).toBeVisible({timeout:45000});await page.locator('#dialogue-next').click();await page.locator('#dialogue-next').click();await expect(page.locator('#journey-modal')).toContainText('Joining reward');await page.locator('#journey-confirm').click();await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await expect(page.locator('#overlay')).toBeVisible();await expect(page.locator('#journey-modal')).toBeHidden();await page.locator('#begin').click();await expect(page.locator('#journey-modal')).toBeVisible();await page.screenshot({path:'test-results/cavern-alert.png'});await page.locator(accept?'#accept-exit-quest':'#decline-exit-quest').click();}
test('seamless cavern opening, treasure, goblins and save',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await opening(page);expect(await page.evaluate(()=>Object.keys(window.trinity.sim.progression.learned))).toEqual(['focused-strike']);expect(await page.evaluate(()=>window.trinity.sim.weapon)).toBe('rapier');
await page.screenshot({path:'test-results/cavern-opening.png'});
await page.evaluate(()=>{const t=window.trinity;t.sim.player.x=-5;t.sim.player.z=3;});await page.keyboard.press('e');expect(await page.evaluate(()=>window.trinity.sim.journey.coins)).toBe(30);await page.keyboard.press('e');expect(await page.evaluate(()=>window.trinity.sim.journey.coins)).toBe(30);
const result=await page.evaluate(()=>{const t=window.trinity,s=t.sim;t.pause(true);const ids=s.enemies.map((e:any)=>e.id).join();for(let z=0;z<=22;z+=.2){s.player.x=0;s.player.z=z;t.dungeon.update([],16);}t.view.update(s,.016);return {ids,after:s.enemies.map((e:any)=>e.id).join(),room:s.journey.room};});expect(result.ids).toBe(result.after);expect(result.room).toBe(1);
await page.evaluate(()=>{const t=window.trinity;t.sim.player.x=0;t.sim.player.z=27;t.sim.lockedId='cavern-1-0';t.pause(false);});await page.waitForTimeout(400);await page.screenshot({path:'test-results/cavern-goblin.png'});await page.evaluate(()=>window.trinity.persist());await page.reload();await expect(page.locator('#begin')).toBeEnabled({timeout:45000});expect(await page.evaluate(()=>window.trinity.sim.journey.quest)).toBe('accepted');expect(errors).toEqual([]);
});
for(const accept of [true,false])test(`exit reward respects quest acceptance ${accept}`,async({page})=>{await opening(page,accept);await page.evaluate(()=>{const t=window.trinity,s=t.sim;t.pause(true);for(const e of s.enemies)s.hitEnemy(e,10000,0,'Normal','completion-test');t.dungeon.update(s.events,16);s.player.x=0;s.player.z=160;s.state.reset();t.dungeon.update([],16);t.pause(false);t.dungeon.interact();});await expect(page.locator('#journey-dialogue')).toContainText('Mira Vale');await page.screenshot({path:`test-results/cavern-mira-${accept}.png`});for(let i=0;i<5;i++)await page.locator('#dialogue-next').click();if(accept){await expect(page.locator('.primer-options section')).toHaveCount(3);await page.locator('[data-primer=renewal]').click();await page.locator('#accept-book').click();expect(await page.evaluate(()=>window.trinity.sim.journey.book)).toBe('renewal');}else{expect(await page.evaluate(()=>window.trinity.sim.journey.book)).toBeNull();await expect(page.locator('.primer-options')).toHaveCount(0);}expect(await page.evaluate(()=>window.trinity.sim.progression.learned.linear)).toBeUndefined();});
