import {test,expect} from '@playwright/test';
import {createTestCharacter,dismissInvitation} from '../uiHelpers';
test('orb guided targeting, boar counter cue, center-mass view and fixed HP silhouette',async({page})=>{
 await page.goto('/?webgl');await createTestCharacter(page);await page.locator('#begin').click();await dismissInvitation(page);
 expect(await page.evaluate(()=>window.trinity.input.bindings.interact[0])).toBe('KeyE');await page.evaluate(()=>{const s=window.trinity.sim;s.player.x=2;s.player.z=-8;});await page.keyboard.press('e');await page.locator('#orb-guided').click();await expect(page.locator('#tutorial')).toContainText('Target your opponent');await page.keyboard.press('Tab');await expect(page.locator('#tutorial-next')).toBeEnabled();await page.locator('#tutorial-next').click();await page.keyboard.down('d');await page.waitForTimeout(450);await page.keyboard.up('d');await expect(page.locator('#tutorial-next')).toBeEnabled();await page.locator('#tutorial-next').click();await expect(page.locator('#tutorial')).toContainText('Quick attacks');await page.locator('#tutorial-exit').click();
 await page.evaluate(()=>{const t=window.trinity,s=t.sim;s.spawnEnemy('boar');s.player.z=.7;s.enemies[0].z=2.5;s.lockedId=s.enemies[0].id;t.view.togglePerspective();document.getElementById('ui')!.classList.add('first-person');});
 await page.waitForTimeout(600);await expect(page.locator('#defense-cue')).toBeVisible();await expect(page.locator('#defense-cue')).toContainText('PARRY Q');await page.screenshot({path:'docs/screenshots/boar-counter-cue.png'});
 await page.waitForFunction(()=>{const s=window.trinity.sim,e=s.enemies[0];return e.pattern&&e.pattern.hits[0]+e.attackStart-s.now<150;},null,{polling:'raf'});await page.keyboard.press('q');await expect.poll(()=>page.evaluate(()=>window.trinity.sim.enemies[0].hp)).toBeLessThan(220);expect(await page.evaluate(()=>window.trinity.sim.player.hp)).toBe(200);
 expect(await page.evaluate(()=>window.trinity.view.camera.beta)).toBeLessThan(1.3);
 await page.evaluate(()=>{window.trinity.sim.reset();window.trinity.sim.player.hp=150;});await page.waitForTimeout(200);const width=await page.locator('#hp').evaluate(e=>e.getBoundingClientRect().width);expect(await page.locator('#hp').evaluate(e=>getComputedStyle(e).clipPath)).toContain('25%');await page.screenshot({path:'docs/screenshots/health-bar-75.png'});
 await page.evaluate(()=>window.trinity.sim.player.hp=90);await page.waitForTimeout(200);expect(await page.locator('#hp').evaluate(e=>e.getBoundingClientRect().width)).toBe(width);expect(await page.locator('#hp').evaluate(e=>getComputedStyle(e).clipPath)).toContain('55%');await page.screenshot({path:'docs/screenshots/health-bar-45.png'});
});
