import {test,expect} from '@playwright/test';
import {createTestCharacter,dismissInvitation} from '../uiHelpers';
test('filled journal resources stay inside tracks and focus loss does not show settings',async({page})=>{
 await page.goto('/?webgl');await createTestCharacter(page);await page.locator('#begin').click();await dismissInvitation(page);await page.evaluate(()=>{window.trinity.sim.player.sp=54;});await page.keyboard.press('m');await page.locator('[data-category=arts]').click();
 for(const value of [1,54,100]){await page.evaluate(v=>window.trinity.sim.player.sp=v,value);await expect(page.locator('.journal-fill-sp')).toHaveCSS('position','static');await expect.poll(()=>page.locator('.journal-fill-sp').evaluate(e=>{const r=e.getBoundingClientRect();return r.height>0&&r.height<12&&r.width<300;})).toBe(true);}
 const box=await page.locator('#personal-detail').boundingBox();expect(box!.height).toBeLessThan(450);expect(box!.width).toBeLessThan(460);await expect(page.locator('.location')).toBeHidden();await page.screenshot({path:'docs/screenshots/compact-skills-clean.png'});
 await page.locator('[data-skill=focused-strike]').click();await expect(page.locator('.selected-art-title')).toContainText('Focused Strike');await page.locator('[data-equip-slot="1"]').click();await page.locator('#tray-close').click();
 await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await expect(page.locator('#overlay')).toHaveClass(/safety-pause/);await expect(page.locator('#open-controls')).toBeHidden();const time=await page.evaluate(()=>window.trinity.sim.now);await page.waitForTimeout(200);expect(await page.evaluate(()=>window.trinity.sim.now)).toBe(time);await page.screenshot({path:'docs/screenshots/focus-pause.png'});await page.locator('#begin').click();await expect(page.locator('#overlay')).toBeHidden();await page.locator('#menu').click();await expect(page.locator('#overlay')).not.toHaveClass(/safety-pause/);
});
