import {test,expect} from '@playwright/test';
test('old saved target controls migrate to E interaction and T switching',async({page})=>{
 await page.goto('/?webgl');await page.locator('#creation-name').fill('Legacy');await page.locator('[name=character][value=man]').check();await page.locator('#character-creation button').click();await expect(page.locator('#begin')).toBeEnabled({timeout:45000});await page.evaluate(()=>window.trinity.persist());
 await page.evaluate(()=>new Promise<void>((resolve,reject)=>{const request=indexedDB.open('trinity',1);request.onsuccess=()=>{const db=request.result,tx=db.transaction('saves','readwrite'),store=tx.objectStore('saves'),read=store.get('combat-lab');read.onsuccess=()=>{const save=read.result;save.settings.bindings.interact=[null,null];save.settings.bindings.switchTarget=['KeyE',null];save.settings.bindings.attack=['KeyK',null];store.put(save,'combat-lab');};tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);};request.onerror=()=>reject(request.error);}));
 await page.reload();await expect(page.locator('#begin')).toBeEnabled({timeout:45000});await page.locator('#open-controls').click();
 await expect(page.getByRole('button',{name:'Interact primary binding',exact:true})).toHaveText('E');await expect(page.getByRole('button',{name:'Switch target primary binding',exact:true})).toHaveText('T');await expect(page.getByRole('button',{name:'Basic attack primary binding',exact:true})).toHaveText('K');
 await page.locator('#controls-close').click();await page.locator('#begin').click();if(await page.locator('#decline-guild-challenge').isVisible())await page.locator('#decline-guild-challenge').click();await page.evaluate(()=>{window.trinity.sim.player.x=2;window.trinity.sim.player.z=-8;});await expect(page.locator('#orb-prompt')).toContainText('E');await page.keyboard.press('e');await expect(page.locator('#training-orb')).toBeVisible();
});

