import {test,expect} from '@playwright/test';
test('woman creation, first-person entry, remapped rack and saved identity',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?webgl');
 await expect(page.locator('#character-creation')).toBeVisible();await page.locator('#creation-name').fill('Aria');await page.locator('[name="character"][value="woman"]').check();await page.locator('#character-creation button').click();
 await expect(page.locator('#begin')).toBeEnabled({timeout:45000});expect(await page.evaluate(()=>window.trinity.view.firstPerson)).toBe(true);expect(await page.evaluate(()=>window.trinity.sim.profile.character)).toBe('woman');
 expect(await page.evaluate(()=>window.trinity.view.loadedAssets)).toContain('/assets/characters/wayfarer_woman.glb');await expect(page.locator('.intro h1')).toHaveText('Training Room');await expect(page.locator('.intro')).toContainText('Guild Challenge');
 await page.locator('#begin').click();await expect(page.locator('#guild-invitation')).toBeVisible();await page.locator('#decline-guild-challenge').click();expect(await page.evaluate(()=>window.trinity.sim.enemies.length)).toBe(0);
 await page.keyboard.press('m');await expect(page.locator('#personal-character-name')).toHaveText('Aria');await expect(page.locator('#character-name')).toHaveCount(0);
 await page.locator('#menu').click();await page.locator('#settings-name').fill('Aria Vale');await page.getByRole('button',{name:'Save name',exact:true}).click();await page.locator('#open-controls').click();await page.getByRole('button',{name:'Interact primary binding',exact:true}).click();await page.keyboard.press('h');await page.locator('#controls-close').click();await page.locator('#perspective').click();await page.locator('#begin').click();
 await page.keyboard.press('m');await page.evaluate(()=>{const t=window.trinity;t.sim.player.x=-8;t.sim.player.z=7;t.view.camera.alpha=.8;t.view.cameraDistance=4;});await expect(page.locator('#rack-prompt')).toContainText('H');await page.keyboard.press('g');await expect(page.locator('#weapon-rack')).toBeHidden();await page.keyboard.press('h');await expect(page.locator('#weapon-rack')).toBeVisible();await page.locator('[data-weapon="greatsword"]').click();await page.locator('#rack-close').click();await expect.poll(()=>page.evaluate(()=>window.trinity.view.equippedWeapon)).toBe('greatsword');await page.screenshot({path:'test-results/woman-greatsword.png'});
 await page.evaluate(()=>window.trinity.persist());await page.reload();await expect(page.locator('#begin')).toBeEnabled({timeout:45000});await expect(page.locator('#character-creation')).toHaveCount(0);expect(await page.evaluate(()=>window.trinity.view.firstPerson)).toBe(true);expect(await page.evaluate(()=>window.trinity.sim.profile.name)).toBe('Aria Vale');expect(await page.evaluate(()=>window.trinity.input.bindings.interact[0])).toBe('KeyH');expect(errors).toEqual([]);
});
test('accepting the Guild Challenge teaches combat and awards Linear with its dash description',async({page})=>{
 await page.goto('/?webgl');await page.locator('#creation-name').fill('Rowan');await page.locator('[name="character"][value="man"]').check();await page.locator('#character-creation button').click();await expect(page.locator('#begin')).toBeEnabled({timeout:45000});await page.locator('#begin').click();await page.locator('#accept-guild-challenge').click();
 await expect(page.locator('#tutorial')).toContainText('GUILD CHALLENGE');expect(await page.evaluate(()=>window.trinity.view.firstPerson)).toBe(true);
 for(let i=0;i<3;i++){await page.keyboard.press('j');await page.waitForTimeout(500);}await page.locator('#tutorial-next').click();
 await page.waitForFunction(()=>{const s=window.trinity.sim,e=s.enemies[0];return e.pattern&&e.attackStart+e.pattern.hits[0]-s.now<180;},null,{polling:'raf'});await page.keyboard.press('Space');await expect(page.locator('#tutorial-next')).toBeEnabled();await page.locator('#tutorial-next').click();
 await page.waitForFunction(()=>{const s=window.trinity.sim,e=s.enemies[0];return e.pattern&&e.attackStart+e.pattern.hits[0]-s.now<110;},null,{polling:'raf'});await page.keyboard.press('q');await expect(page.locator('#tutorial-next')).toBeEnabled();await page.locator('#tutorial-next').click();
 for(let i=0;i<2;i++){await page.keyboard.down('1');await page.waitForFunction(()=>{const s=window.trinity.sim;return s.art&&s.now-s.art.start>500;},null,{polling:'raf'});await page.keyboard.up('1');await expect(page.locator('#tutorial-next')).toBeEnabled();await page.locator('#tutorial-next').click();}
 await expect(page.locator('#guild-invitation')).toContainText('Linear learned');await expect(page.locator('#guild-invitation')).toContainText('6 m');await expect(page.locator('#guild-invitation')).toContainText('1 m');expect(await page.evaluate(()=>Object.keys(window.trinity.sim.progression.learned))).toEqual(['focused-strike','linear']);await page.locator('#reward-linear-equip').click();await expect(page.locator('#loadout-tray')).toBeVisible();
});
