import {test,expect} from '@playwright/test';
import {createTestCharacter,dismissInvitation} from '../uiHelpers';
test('entrance orb starts repeat opponents and skills select details then slots',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?webgl');await createTestCharacter(page);await page.locator('#begin').click();await dismissInvitation(page);
 await page.keyboard.press('e');await expect(page.locator('#training-orb')).toBeHidden();
 await page.evaluate(()=>{const t=window.trinity;t.sim.player.x=2;t.sim.player.z=-8;t.input.bindings.interact=['KeyH'];});await expect(page.locator('#orb-prompt')).toContainText('H');await page.keyboard.press('h');await expect(page.locator('#training-orb')).toBeVisible();await page.screenshot({path:'docs/screenshots/training-orb.png'});await page.locator('[data-opponent=sentinel]').click();expect(await page.evaluate(()=>window.trinity.sim.enemies[0].species)).toBe('sentinel');
 await page.evaluate(()=>{const s=window.trinity.sim;s.enemies[0].hp=0;s.enemies[0].state='Dead';s.player.x=2;s.player.z=-8;});await page.keyboard.press('h');await page.locator('[data-opponent=boar]').click();await expect(page.locator('.enemy-title b')).toHaveText('Woodland Boar');
 await page.evaluate(()=>{const s=window.trinity.sim;s.flags.freezeAI=true;s.player.z=-1;window.trinity.view.camera.alpha+=.55;s.autoFaceTarget=false;s.lockedId=null;});await page.waitForTimeout(1200);await page.screenshot({path:'docs/screenshots/woodland-boar.png'});expect(await page.evaluate(()=>window.trinity.view.assetErrors)).toEqual([]);expect(await page.evaluate(()=>window.trinity.view.actors.get(window.trinity.sim.enemies[0].id).sword.isEnabled())).toBe(false);
 await page.evaluate(()=>{window.trinity.sim.reset();window.trinity.sim.progression.learned.linear='induction';});await page.keyboard.press('m');await page.locator('[data-category=arts]').click();await expect(page.locator('[data-skill]')).toHaveCount(2);await expect(page.locator('#personal-detail .skill-card')).toHaveCount(0);await page.locator('[data-skill=linear]').click();await page.locator('[data-equip-slot="1"]').click();expect(await page.evaluate(()=>window.trinity.sim.loadout[1])).toBe('linear');await page.locator('[data-equip-slot="2"]').click();expect(await page.evaluate(()=>window.trinity.sim.loadout)).toEqual(['focused-strike',null,'linear',null]);await page.screenshot({path:'docs/screenshots/skill-selection.png'});await page.evaluate(()=>{window.trinity.view.togglePerspective();document.getElementById('ui')!.classList.add('first-person');});await page.screenshot({path:'docs/screenshots/skill-selection-first-person.png'});await page.setViewportSize({width:640,height:720});expect(await page.locator('#loadout-tray').evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);await page.evaluate(()=>window.trinity.persist());expect(errors).toEqual([]);
});
