import {createTestCharacter,dismissInvitation,startCombatTrial} from '../uiHelpers';
import {test,expect} from '@playwright/test';
test('character name, five equipment and inventory slots, discovery, chats and layered pause',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?webgl');await createTestCharacter(page);await expect(page.locator('#begin')).toBeEnabled({timeout:45000});await page.locator('#begin').click();await dismissInvitation(page);await page.keyboard.press('m');
 await expect(page.locator('[data-equipment]')).toHaveCount(5);await expect(page.locator('[data-pocket]')).toHaveCount(5);
 await expect(page.locator('#character-name')).toHaveCount(0);await page.locator('#menu').click();await page.locator('#settings-name').fill('Aria');await page.getByRole('button',{name:'Save name',exact:true}).click();await page.locator('#begin').click();await dismissInvitation(page);await expect(page.locator('.player-name b')).toHaveText('Aria');
 await page.locator('#friends-menu').click();await expect(page.locator('#personal-detail')).toContainText('Warden Ilyra');await page.locator('#manual-menu').click();await expect(page.locator('#personal-detail')).toContainText('No creatures recorded');
 await page.locator('#character-menu').click();await page.locator('#pocket-select').selectOption('4');await page.locator('#assign-supply').click();await expect(page.locator('[data-pocket="4"]')).toContainText('HP');await expect(page.locator('[data-pocket="0"]')).toHaveText('+');
 await page.evaluate(()=>window.trinity.sim.player.hp=100);await page.locator('#use-supply').click();expect(await page.evaluate(()=>window.trinity.sim.player.hp)).toBe(160);await expect(page.locator('[data-pocket="4"]')).toContainText('×1');
 await page.locator('[data-category="arts"]').click();await expect(page.locator('#edit-arts')).toHaveCount(0);await page.locator('#skill-books>summary').click();await page.locator('[data-book-node=linear]').click();await expect(page.locator('.book-node-detail')).toContainText('12 eligible basic hits');await expect(page.locator('.book-preview')).toContainText('NOT OWNED');await page.locator('#skill-books>summary').click();await page.locator('[data-skill=focused-strike]').click();await expect(page.locator('#loadout-tray')).toContainText('6×');await expect(page.locator('#loadout-tray')).toContainText('Basic Art');await page.locator('#tray-close').click();
 await page.locator('#map-menu').click();await expect(page.locator('.floor-map')).toBeVisible();const time=await page.evaluate(()=>window.trinity.sim.now);await page.keyboard.down('w');await page.waitForTimeout(300);await page.keyboard.up('w');expect(await page.evaluate(()=>window.trinity.sim.now)).toBeGreaterThan(time+100);
 await page.locator('#menu').click();await expect(page.locator('#overlay')).toBeVisible();const frozen=await page.evaluate(()=>window.trinity.sim.now);await page.waitForTimeout(200);expect(await page.evaluate(()=>window.trinity.sim.now)).toBe(frozen);await page.locator('#open-controls').click();await expect(page.locator('#controls-menu')).toBeVisible();await page.locator('#controls-close').click();await page.locator('#perspective').click();await page.locator('#begin').click();await dismissInvitation(page);await expect(page.locator('#personal-artifact')).toBeVisible();
 await page.evaluate(()=>{const s=window.trinity.sim;s.progression.tutorialCompleted=true;s.spawnEnemy();s.flags.freezeAI=true;});await page.locator('#friends-menu').click();await expect(page.locator('#personal-detail')).toContainText('1 contact');await page.getByText('Chats with Ilyra',{exact:true}).click();await page.locator('[data-chat="guild"]').click();await expect(page.locator('#chat-history')).toContainText('Training Room');await page.locator('#manual-menu').click();await expect(page.locator('#personal-detail')).toContainText('Aether Sentinel');
 await page.evaluate(()=>window.trinity.persist());await page.reload();await expect(page.locator('#begin')).toBeEnabled();await page.locator('#begin').click();await dismissInvitation(page);await page.keyboard.press('m');await expect(page.locator('#personal-character-name')).toHaveText('Aria');await expect(page.locator('[data-pocket="4"]')).toContainText('×1');await page.locator('#manual-menu').click();await expect(page.locator('#personal-detail')).toContainText('Aether Sentinel');
 await startCombatTrial(page);await page.locator('#menu').click();await expect(page.locator('#overlay')).toBeHidden();await expect(page.locator('#notice')).toContainText('Finish the trial');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await expect(page.locator('#overlay')).toBeVisible();expect(errors).toEqual([]);
});
