import {test,expect} from '@playwright/test';
test('reference panels and town remain usable at desktop and compact widths',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?webgl');await page.locator('#creation-name').fill('Arden');await page.locator('[name=character][value=man]').check();await page.locator('#character-creation button').click();await expect(page.locator('#dialogue-next')).toBeVisible({timeout:45000});await page.locator('#dialogue-next').click();await page.locator('#dialogue-next').click();await page.locator('#journey-confirm').click();await page.locator('#accept-exit-quest').click();
 await page.keyboard.press('m');await page.evaluate(()=>{const t=window.trinity;t.input.autoMouseLook=false;t.sim.flags.freezeAI=true;t.sim.journey.facts.push('boss','gate-town-side');t.sim.player.x=0;t.sim.player.z=153;t.sim.lockedId=null;t.sim.progression.learned.linear='induction';t.view.camera.alpha=-Math.PI/2;t.view.camera.beta=1.5;});await page.waitForTimeout(6500);
 await page.locator('[data-category=arts]').click();await page.locator('[data-skill=linear]').click();await expect(page.locator('[data-select-art]')).toHaveCount(2);await page.screenshot({path:'docs/screenshots/reference-menu-town.png'});
 await page.locator('[data-select-art="focused-strike"]').click();await expect(page.locator('.selected-art-title')).toContainText('Focused Strike');await page.locator('[data-art-filter=combat]').click();await expect(page.locator('.skill-browser-list')).toContainText('No learned');await page.locator('[data-art-filter=all]').click();
 await page.setViewportSize({width:640,height:720});await expect(page.locator('#tray-close')).toBeVisible();expect(await page.locator('#loadout-tray').evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);await page.screenshot({path:'docs/screenshots/reference-menu-compact.png'});
 await page.setViewportSize({width:1440,height:900});await page.keyboard.press('m');await page.screenshot({path:'docs/screenshots/reference-town.png'});expect(errors).toEqual([]);expect(await page.evaluate(()=>window.trinity.view.assetErrors)).toEqual([]);
});
