import {describe,it,expect} from 'vitest';
import {CombatSimulation} from '../src/combat/simulation';
import {defaultSave,migrateSave} from '../src/save/save';
import {weapons} from '../src/data/weapons';
import {awardFieldSkills,freshProgression} from '../src/progression/guild';
const tick=(s:CombatSimulation,ms:number)=>{for(let n=0;n<ms;n+=10)s.update(Math.min(10,ms-n));};
function room(){const s=new CombatSimulation();s.flags.freezeAI=true;s.player.z=0;s.enemies[0].z=2;s.player.sp=100;return s;}
function linear(at:number){const s=room();s.progression.learned.linear='induction';s.loadout=['linear',null,null,null];s.activateArt(0);tick(s,at);s.releaseArt(0);tick(s,850);return s;}
describe('training skills and three-weapon rack',()=>{
 it('starts with only Focused Strike and keeps induction reward through saves',()=>{const d=defaultSave();expect(Object.keys(d.progression.learned)).toEqual(['focused-strike']);d.progression.tutorialCompleted=true;const restored=migrateSave(d);expect(Object.keys(restored.progression.learned)).toEqual(['focused-strike','linear']);});
 it('hits only one nearby enemy with the narrow starter strike',()=>{const s=room();s.spawnEnemy();s.enemies[1].x=0;s.enemies[1].z=2.8;s.activateArt(0);tick(s,520);s.releaseArt(0);tick(s,500);expect(s.enemies.filter(e=>e.hp<e.maxHp)).toHaveLength(1);});
 it('Perfect Linear passes through while Good stops short and Miss stays still',()=>{const p=linear(680),g=linear(580),m=linear(0);expect(p.player.z).toBeCloseTo(6,4);expect(p.player.z).toBeGreaterThan(p.enemies[0].z);expect(g.player.z).toBeLessThan(g.enemies[0].z);expect(g.enemies[0].hp).toBeLessThan(460);expect(p.enemies[0].hp).toBeLessThan(g.enemies[0].hp);expect(p.events.filter(e=>e.type==='hit')).toHaveLength(1);expect(m.enemies[0].hp).toBe(460);expect(m.player.z).toBe(0);});
 it('retains equipment and rejects incompatible sword Arts',()=>{const s=room();s.progression.learned['crescent-break']='legacy';s.loadout=['crescent-break',null,null,null];expect(s.setWeapon('rapier')).toBe(true);expect(s.loadout).toEqual(['focused-strike',null,null,null]);expect(s.equipLoadout(['crescent-break',null,null,null])).toBe(false);const d=defaultSave();d.weapon='rapier';expect(migrateSave(d).weapon).toBe('rapier');expect(Object.keys(weapons)).toEqual(['sword','rapier','greatsword']);expect(weapons.greatsword.damage).toBeGreaterThan(weapons.rapier.damage);});
 it('earns skills in normal combat but never after debug resource grants',()=>{const s=new CombatSimulation();s.player.z=0;s.enemies[0].z=2;s.enemies[0].until=1e9;for(let i=0;i<20;i++){s.pressAttack();tick(s,500);}expect(s.progression.learned['crescent-break']).toBe('field practice');const d=new CombatSimulation();d.invalidateRewards('Debug SP');d.hitEnemy(d.enemies[0],5,0,'Normal','basic');expect(d.progression.field.hits).toBe(0);});
 it('provides regular-play routes to every learned Art',()=>{const p=freshProgression();p.field={hits:20,evades:6,parries:8,breaks:4,kills:8};awardFieldSkills(p);expect(Object.keys(p.learned)).toHaveLength(7);});
 it('Aether creates lateral space while Stillwater restores stamina only on contact',()=>{const a=room();a.progression.learned['aether-step']='positioning';a.loadout=['aether-step',null,null,null];a.activateArt(0);tick(a,440);a.releaseArt(0);tick(a,310);expect(a.player.x).toBeCloseTo(2,4);expect(a.enemies[0].hp).toBeLessThan(460);const s=room();s.progression.learned['stillwater-return']='countering';s.loadout=['stillwater-return',null,null,null];s.activateArt(0);tick(s,400);s.player.stamina=40;s.lastStaminaUse=s.now;s.releaseArt(0);tick(s,160);expect(s.player.stamina).toBe(54);});
});
