import {gmCatalog,originalCatalog,validateCatalog,applyCatalog,type GMCatalog} from '../data/gm';
import type {CombatSimulation} from '../combat/simulation';
const key='trinity-gm-items-v1';
export class GMMenu {
 panel=document.createElement('section');private draft:GMCatalog=structuredClone(gmCatalog);private selected='weapons.sword';private active=false;
 constructor(private sim:CombatSimulation){
  this.panel.id='gm-menu';this.panel.hidden=true;this.panel.setAttribute('role','dialog');this.panel.setAttribute('aria-label','GM item editor');document.querySelector('#ui')!.append(this.panel);
  const button=document.createElement('button');button.id='open-gm';button.textContent='GM mode · item editor';document.querySelector('.intro')!.append(button);button.onclick=()=>{this.draft=structuredClone(gmCatalog);this.panel.hidden=false;this.render();};
  try{const saved=JSON.parse(localStorage.getItem(key)??'null');if(saved?.enabled){applyCatalog(validateCatalog(saved.catalog));this.active=true;sim.gmMode=true;}}catch{localStorage.removeItem(key);}
 }
 private render(){
  this.panel.innerHTML=`<div class="tray-heading"><h2>GM item editor</h2><button id="gm-close">Close</button></div><p>Edit local item balance. GM combat cannot earn progression rewards. Close this window to resume play.</p><label><input type="checkbox" id="gm-enabled" ${this.active?'checked':''}> Enable GM mode</label><label>Item<select id="gm-item"></select></label><form id="gm-form"><div id="gm-fields"></div><button type="submit">Apply & save locally</button></form><button id="gm-reset">Restore shipped item values</button><button id="gm-export">Download tuned item bank</button><p id="gm-status" role="status">${this.active?'GM enabled':'Normal play · enable GM to edit'}</p>`;
  const select=this.panel.querySelector<HTMLSelectElement>('#gm-item')!;
  for(const [group,items] of Object.entries(this.draft))for(const [id,item] of Object.entries(items)){const option=document.createElement('option');option.value=group+'.'+id;option.textContent=group+' / '+item.name;select.append(option);}select.value=this.selected;select.onchange=()=>{this.capture();this.selected=select.value;this.fields();};
  this.panel.querySelector<HTMLButtonElement>('#gm-close')!.onclick=()=>this.panel.hidden=true;
  this.panel.querySelector<HTMLInputElement>('#gm-enabled')!.onchange=e=>{if(this.sim.encounter.active||this.sim.practiceMode||this.sim.enemies.some(e=>e.hp>0)){(e.target as HTMLInputElement).checked=this.active;this.status('Finish the encounter before changing GM mode.');return;}this.active=(e.target as HTMLInputElement).checked;this.sim.gmMode=this.active;if(!this.active){applyCatalog(originalCatalog);localStorage.removeItem(key);this.draft=structuredClone(gmCatalog);}this.fields();this.status(this.active?'GM enabled · adjust values then apply.':'Normal item values restored.');};
  this.panel.querySelector<HTMLFormElement>('#gm-form')!.onsubmit=e=>{e.preventDefault();if(!this.active)return;try{this.capture();const data=validateCatalog(this.draft);localStorage.setItem(key,JSON.stringify({enabled:true,catalog:data}));applyCatalog(data);this.sim.invalidateRewards('GM item tuning');this.status('Applied and saved. Charts and combat use these values.');}catch(error){this.status(String(error));}};
  this.panel.querySelector<HTMLButtonElement>('#gm-reset')!.onclick=()=>{if(!this.active)return;this.draft=structuredClone(originalCatalog);applyCatalog(this.draft);localStorage.setItem(key,JSON.stringify({enabled:true,catalog:this.draft}));this.fields();this.status('Shipped item values restored.');};
  this.panel.querySelector<HTMLButtonElement>('#gm-export')!.onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(gmCatalog,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='trinity-tuned-items.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};this.fields();
 }
 private item():any{const [group,id]=this.selected.split('.');return (this.draft as any)[group][id];}
 private fields(){const root=this.panel.querySelector('#gm-fields')!;root.replaceChildren();const walk=(obj:any,path:string[])=>{for(const [k,v] of Object.entries(obj)){const full=[...path,k];if(v&&typeof v==='object'){walk(v,full);continue;}const label=document.createElement('label');label.textContent=full.join(' · ')+(['halfArc','arc'].includes(k)?' · full fan degrees':'');const input=document.createElement('input');input.dataset.path=full.join('.');input.type=typeof v==='number'?'number':typeof v==='boolean'?'checkbox':'text';if(input.type==='number'){input.step='any';input.min='0';}input.value=String(['halfArc','arc'].includes(k)?Number(v)*360/Math.PI:v);if(['halfArc','arc'].includes(k))input.dataset.angle='true';input.checked=v===true;input.disabled=!this.active||['id','model','weapon','kind','motion','input','practiceArt'].includes(k);label.append(input);root.append(label);}};walk(this.item(),[]);}
 private capture(){for(const input of this.panel.querySelectorAll<HTMLInputElement>('[data-path]')){const path=input.dataset.path!.split('.');let obj=this.item();for(const part of path.slice(0,-1))obj=obj[part];obj[path.at(-1)!]=input.type==='number'?Number(input.value)*(input.dataset.angle?Math.PI/360:1):input.type==='checkbox'?input.checked:input.value;}}
 private status(text:string){this.panel.querySelector('#gm-status')!.textContent=text;}
}
