import {skillCard} from './skillCard';
import {arts} from '../data/arts';
import {challenges,canStart,guildStory,type ChallengeId,type MasteryChoice} from '../progression/guild';
import type {CombatSimulation} from '../combat/simulation';
export class GuildBoard {
 panel=document.createElement('section');tracker=document.createElement('aside');seenResult=0;tab:'journey'|'arts'='journey';
 get visible(){return !this.panel.hidden;}
 constructor(private sim:CombatSimulation,private pause:(value:boolean)=>void,private persist:()=>void,private live:()=>boolean=()=>false){this.panel.id='guild-board';this.panel.hidden=true;this.panel.setAttribute('aria-label','Personal Guild menu');this.tracker.id='trial-tracker';this.tracker.hidden=true;document.getElementById('ui')!.append(this.panel,this.tracker);}
 open(){this.pause(!this.live());document.getElementById('overlay')!.hidden=true;this.panel.hidden=false;document.getElementById('ui')!.classList.add('journal-open');this.panel.classList.toggle('personal-live',this.live());this.render();this.panel.scrollTop=0;}
 close(){document.getElementById('ui')!.classList.remove('journal-open');this.panel.hidden=true;this.pause(false);}
 observe(){const e=this.sim.encounter,s=e.stats;this.tracker.hidden=!e.active;if(e.active)this.tracker.textContent=`${challenges[e.challenge!].name} · ${e.challenge==='positioning'?`${s.basicHits}/3 strikes · ${s.evades}/1 evade`:e.challenge==='breaking'?`${s.artHits}/1 Art · ${s.breaks}/1 Break`:e.challenge==='countering'?`${s.parries}/3 counters`:`${s.defeats}/2 sentinels`}${e.eligible?'':' · Practice'}`;if(e.id!==this.seenResult&&(e.result==='completed'||e.result==='failed')){this.seenResult=e.id;this.sim.reset();this.tab='journey';this.persist();this.open();}}
 render(){
 const sim=this.sim,p=sim.progression,e=sim.encounter,s=e.stats,reward=e.challenge?arts[challenges[e.challenge].reward]:null,finished=e.result==='completed'&&e.eligible;
 const artInfo=(id:string)=>skillCard(arts[id],sim);
 this.panel.innerHTML=`<div class="guild-sheet"><div class="guild-heading"><div><small>LANTERN GUILD · ${this.live()?'WORLD LIVE':'PAUSED'}</small><h1>${p.completed.includes('trial')?'Wayfarer’s journal':'The Lantern Oath'}</h1></div><button id="guild-close" aria-label="Close Guild menu">×</button></div>
 <nav class="guild-tabs"><button data-tab="journey" aria-pressed="${this.tab==='journey'}">Journey <small>${p.completed.length}/4</small></button><button data-tab="arts" aria-pressed="${this.tab==='arts'}">Arts & loadout</button></nav>
 <section ${this.tab==='journey'?'':'hidden'}>
 ${e.result==='completed'||e.result==='failed'?`<section class="guild-result"><small>${finished?'CHALLENGE COMPLETE':e.result==='failed'?'TRY AGAIN':'PRACTICE COMPLETE'}</small><h2>${e.challenge?challenges[e.challenge].name:''}</h2><p>${finished?guildStory[e.challenge!].debrief:e.reason||'Ilyra: Take a breath. An oath is built on returning, not on never falling.'}</p>${finished&&reward?`<div class="guild-reward"><small>${e.rewardNew?'ART ACQUIRED':'ART LEARNED'}</small>${artInfo(reward.id)}<button id="reward-equip">View & equip ${reward.name}</button>${e.challenge==='trial'?'<p class="guild-title-earned">✧ Title earned · Wayfarer</p>':''}</div>`:''}<details class="nested-info"><summary>Combat record</summary><p>${s.parries} perfect counters · ${s.failedCounters} failed counters · ${Math.round(s.damageTaken)} damage taken · ${s.breaks} Breaks · ${s.perfect+s.good}/${s.artPhases} successful timing events</p></details></section>`:''}
 <div class="guild-invitation"><small>WARDEN ILYRA</small><p>Training Room · Guild Hall · Town of Beginnings</p><details class="nested-info"><summary>Why take the oath?</summary><p>Complete Ilyra’s induction to learn Linear early. You can also learn Arts through regular combat practice here; the larger Town of Beginnings is planned outside this training room. The Lantern Guild escorts travellers between the last watchfires. Its hall was built around an old oathstone: no one walks the dark road alone. Ilyra asks you to earn that promise, one lesson at a time.</p><p>Complete the four trials to earn the <b>Wayfarer</b> title and <b>Wayfarer’s Oath</b>, your first two-event Combat Art.</p></details></div>
 <div class="guild-challenges">${(Object.keys(challenges) as ChallengeId[]).map(id=>{const c=challenges[id];return `<article><small>${guildStory[id].chapter}</small><h3>${p.completed.includes(id)?'✓ ':''}${c.name}</h3><p>${c.description}</p><details class="nested-info"><summary>Ilyra’s guidance</summary><p>${guildStory[id].brief}</p></details><div class="challenge-reward"><small>REWARD</small>${artInfo(c.reward)}</div><button data-challenge="${id}" ${canStart(p,id)?'':'disabled'}>${canStart(p,id)?p.completed.includes(id)?'Replay trial':'Begin trial':'Complete previous trial'}</button></article>`;}).join('')}</div></section>
 <section ${this.tab==='arts'?'':'hidden'}><h2>Four slots. Your style.</h2><p class="subtle">Equip between trials. Highlighted names expand.</p><div class="guild-slots">${sim.loadout.map((id,i)=>`<label>Slot ${i+1}<select data-equip="${i}" ${e.active?'disabled':''}><option value="">Empty</option>${Object.values(arts).filter(a=>p.learned[a.id]&&(a.weapon==='any'||a.weapon===sim.weapon)).map(a=>`<option value="${a.id}" ${id===a.id?'selected':''}>${a.name}</option>`).join('')}</select></label>`).join('')}</div><button id="guild-equip" ${e.active?'disabled':''}>Save loadout</button><p id="guild-message" role="status"></p>
 <h2>Known skills</h2><a href="/data/skill-bank.json" download="trinity-skill-bank.json">Download complete skill bank</a>${Object.values(arts).filter(a=>p.learned[a.id]).map(a=>`<article class="collection-row ${p.learned[a.id]?'learned':'locked'}"><small>${p.learned[a.id]?'LEARNED':'LOCKED · '+Object.values(challenges).find(c=>c.reward===a.id)?.name}</small>${artInfo(a.id)}</article>`).join('')}
 <details class="nested-info mastery"><summary>Crescent mastery <small>${Math.min(2,p.masterySources.length)}/2</small></summary><p>Land a Good or Perfect Crescent hit while completing two different trials. Each trial gives one credit. Choose one modifier between trials.</p><div class="guild-mastery">${([['recovery','Swift recovery','200 ms recovery'],['break','Heavy commitment','35% more Break · 460 ms recovery']] as const).map(([id,name,detail])=>`<button data-mastery="${id}" aria-pressed="${p.masteryChoice===id}" ${p.masterySources.length<2||e.active?'disabled':''}>${name}<small>${detail}</small></button>`).join('')}</div></details></section></div>`;
 this.panel.querySelector<HTMLButtonElement>('#guild-close')!.onclick=()=>this.close();
 this.panel.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b=>b.onclick=()=>{this.tab=b.dataset.tab as typeof this.tab;this.render();b.blur();});
 const rewardButton=this.panel.querySelector<HTMLButtonElement>('#reward-equip');if(rewardButton)rewardButton.onclick=()=>{this.tab='arts';this.render();};
 this.panel.querySelectorAll<HTMLButtonElement>('[data-challenge]').forEach(b=>b.onclick=()=>{if(sim.beginChallenge(b.dataset.challenge as ChallengeId))this.close();});
 this.panel.querySelector<HTMLButtonElement>('#guild-equip')!.onclick=()=>{const ids=[...this.panel.querySelectorAll<HTMLSelectElement>('[data-equip]')].map(el=>el.value||null),ok=sim.equipLoadout(ids);this.panel.querySelector('#guild-message')!.textContent=ok?'Loadout saved.':'Choose unique learned Arts and finish your current action or trial first.';if(ok)this.persist();};
 this.panel.querySelectorAll<HTMLButtonElement>('[data-mastery]').forEach(b=>b.onclick=()=>{if(!e.active&&p.masterySources.length>=2){p.masteryChoice=b.dataset.mastery as MasteryChoice;this.persist();this.render();}});
 }
}
