import {supplies} from '../data/items';
import {bookLibrary,bindBookLibrary} from './skillBooks';
import type {CombatSimulation} from '../combat/simulation';
import {arts} from '../data/arts';
import {physicalDamage} from '../data/balance';


export class PersonalMenu {
 panel=document.createElement('section');detail=document.createElement('section');branch=document.createElement('nav');
 private category='items';private signature='';private slot=0;private item='health';
 constructor(private sim:CombatSimulation,private editArts:(id?:string)=>void,private persist:()=>void){
  this.panel.id='personal-artifact';this.panel.setAttribute('aria-label','Character equipment');
  this.panel.innerHTML=`<div class="artifact-title"><span id="personal-character-name"></span><small>CHARACTER / EQUIPMENT</small></div>
  <div class="equipment-body"><svg viewBox="0 0 260 280" role="img" aria-label="Character silhouette"><ellipse cx="130" cy="252" rx="43" ry="5" fill="#526169" opacity=".18"/><g class="body-silhouette"><circle cx="130" cy="65" r="13"/><path d="M116 82 Q130 77 144 82 L155 132 151 159 142 131 142 165 155 245 137 245 130 188 123 245 105 245 118 165 118 131 109 159 105 132Z"/></g></svg>
  ${['Head','Right hand','Left hand','Body','Feet'].map((name,i)=>`<button class="body-slot body-slot-${i}" data-equipment="${i}" title="${name}" aria-label="Inspect ${name}"><i>◇</i><span>${name}</span></button>`).join('')}</div>
  <div class="pocket-label">QUICK INVENTORY</div><div class="pocket-row">${[0,1,2,3,4].map(i=>`<button data-pocket="${i}" aria-label="Inventory slot ${i+1}"></button>`).join('')}</div><div class="equipment-description"><small>EQUIPPED WEAPON</small><h2 id="personal-weapon"></h2><p id="personal-weapon-stats"></p><small>Visit the weapon rack to change your blade.</small></div>`;
  this.detail.id='personal-detail';this.detail.setAttribute('aria-label','Personal information');this.branch.id='character-branch';
  this.branch.innerHTML=`<button data-category="items">▣ &nbsp; Items</button><button data-category="arts">⚔ &nbsp; Skills</button><button data-category="equipment">◇ &nbsp; Equipment</button>`;
  document.querySelector('#ui')!.append(this.panel,this.branch,this.detail);
  this.panel.querySelectorAll<HTMLButtonElement>('[data-equipment]').forEach(b=>b.onclick=()=>{this.open('equipment');this.detail.querySelectorAll<HTMLDetailsElement>('details')[Number(b.dataset.equipment)]!.open=true;});
  this.panel.querySelectorAll<HTMLButtonElement>('[data-pocket]').forEach(b=>b.onclick=()=>{this.slot=Number(b.dataset.pocket);this.item=sim.profile.pockets[this.slot]??'health';this.open('items');});
  this.branch.querySelectorAll<HTMLButtonElement>('[data-category]').forEach(b=>b.onclick=()=>this.open(b.dataset.category!));
  for(const [id,icon,label,category] of [['character-menu','♟','Character','items'],['friends-menu','♟♟','Friends','friends'],['map-menu','⌖','Map','map'],['manual-menu','▤','Monster manual','manual']]){
   const b=document.createElement('button');b.id=id;b.className='quiet fantasy-icon';b.dataset.icon=icon;b.textContent=label;b.setAttribute('aria-label',label);b.onclick=()=>this.open(category);document.querySelector('header')!.append(b);
  }
  this.open('items');
 }
 private heading(title:string){return `<div class="personal-detail-heading"><h2>${title}</h2><button id="personal-detail-close" aria-label="Close information">×</button></div>`;}
 open(category:string){this.category=category;this.detail.hidden=false;this.branch.classList.toggle('expanded',['items','arts','equipment'].includes(category));this.render();}
 private render(){
  const s=this.sim,p=s.profile;let html='';
  if(this.category==='items'){
   html=this.heading('Items')+`<p class="subtle">Training supplies · use between encounters.</p><div class="inventory-list">${['health','stamina'].map(id=>`<button data-item="${id}" aria-pressed="${this.item===id}">${supplies[id as 'health'].name} <b>×${p.potions[id as 'health']}</b></button>`).join('')}</div><article><h3>${supplies[this.item as 'health'].name}</h3><p>Restores ${this.item==='health'?supplies.health.restore+' HP':supplies.stamina.restore+' stamina'}. Consumed on use. Cannot be used during lessons or encounters.</p><button id="use-supply">Use supply</button><p id="supply-status" role="status"></p><label>Accessible inventory slot<select id="pocket-select">${p.pockets.map((_,i)=>`<option value="${i}" ${this.slot===i?'selected':''}>Slot ${i+1}</option>`).join('')}</select></label><button id="assign-supply">Assign here</button><button id="clear-pocket">Clear slot</button></article>`;
  }else if(this.category==='arts')html=this.heading('Skills')+`<p class="subtle">Basic Arts work with any weapon. Combat Arts may require a weapon or class. Skill Books open themed trees. Select a skill to inspect and equip it.</p><div class="skill-name-list">${Object.values(arts).filter(a=>s.progression.learned[a.id]).map(a=>`<button data-skill="${a.id}"><span>${a.name}</span><small>${s.loadout.includes(a.id)?'Equipped · '+(s.loadout.indexOf(a.id)+1):'View details'} ›</small></button>`).join('')}</div>${bookLibrary(s)}<a href="/data/skill-bank.json" download>Download skill bank</a>`;
  else if(this.category==='equipment')html=this.heading('Equipment')+this.equipment().map(([slot,name,desc])=>`<details class="nested-info"><summary>${slot}<small>${name}</small></summary><p>${desc}</p></details>`).join('');
  else if(this.category==='friends'){
   const done=s.progression.tutorialCompleted;
   html=this.heading('Friends')+'<p>1 contact</p><details class="nested-info" open><summary>Warden Ilyra<small>Guild mentor · NPC</small></summary><p>Ilyra prepares new adventurers for the roads beyond town.</p><p>Location: Guild Hall · Town of Beginnings · Floor 1.</p><h3>Current quests</h3>'+(done?'<p>No open quests.</p>':'<article><h4>Guild Combat Trial</h4><p>Touch the entrance orb in the Training Room. Learn targeting, movement, basic attacks, dodging, parrying, countering and Combat Arts.</p><p>Reward: Linear — Perfect dashes 6 m through a target; Good deals 60% damage and travels 1 m.</p></article>')+'<details class="nested-info"><summary>Completed quests · '+(done?'1':'0')+'</summary>'+(done?'<p>✓ Guild Combat Trial</p><p>Learned Linear by completing Ilyra’s combat induction.</p>':'<p>No completed quests yet.</p>')+'</details><details><summary>Chats with Ilyra</summary><button data-chat="guild">What is the Lantern Guild?</button><button data-chat="oath">What are Skill Books?</button><div id="chat-history">'+p.chats.map(id=>this.chat(id)).join('')+'</div></details></details>';
  }else if(this.category==='map')html=this.heading('Floor 1 · Known map')+`<p>Current location: Training Room</p><p>Known from the Guild: Town of Beginnings. The surrounding town is not yet playable.</p><svg class="floor-map" viewBox="0 0 280 280" role="img" aria-label="Explored training room map"><rect width="280" height="280" fill="#5b6b6c"/>${p.explored.map(v=>{const [x,z]=v.split(',').map(Number);return `<rect x="${140+x*32-16}" y="${140-z*32-16}" width="32" height="32" fill="#dbe5dd" stroke="#bac8c2"/>`;}).join('')}<circle cx="140" cy="140" r="110" fill="none" stroke="#f1e4ae"/><rect x="71" y="63" width="10" height="10" fill="#d7b94d"/><circle id="map-player" cx="${140+s.player.x*8}" cy="${140-s.player.z*8}" r="5" fill="#208db3"/></svg><p>Blue: you · Gold: known weapon rack · Dark: unexplored</p>`;
  else html=this.heading('Monster manual')+(p.sentinelSeen?`<details class="nested-info" open><summary>Aether Sentinel<small>Training construct · encountered</small></summary><p>Found in the Training Room during lessons and trials.</p><p>Read the weapon animation for basic attacks. Gold warnings can be parried; red sweeps require a dodge. Fill Break to create an opening.</p><p>Recorded victories: ${s.counters.kills} · Perfect counters: ${s.counters.parries}</p></details>`:p.boarSeen?'':'<p>No creatures recorded. Begin a lesson or Guild challenge to encounter a training construct.</p>');
  if(this.category==='manual'&&p.boarSeen)html+=`<details class="nested-info" open><summary>Woodland Boar<small>Training beast · encountered</small></summary><p>220 HP. A quick tusk jab can be parried. Its wider, red head sweep must be dodged. Punish the long recovery.</p></details>`;this.detail.innerHTML=html;bindBookLibrary(this.detail,s);this.detail.querySelector<HTMLButtonElement>('#personal-detail-close')!.onclick=()=>this.detail.hidden=true;
  this.detail.querySelectorAll<HTMLButtonElement>('[data-item]').forEach(b=>b.onclick=()=>{this.item=b.dataset.item!;this.render();});
  const use=this.detail.querySelector<HTMLButtonElement>('#use-supply');if(use)use.onclick=()=>{const id=this.item as 'health'|'stamina';let result='';if(s.encounter.active||s.practiceMode||s.enemies.some(e=>e.hp>0)||!s.free)result='Finish the encounter first.';else if(p.potions[id]<=0)result='No supplies remaining.';else if(id==='health'?s.player.hp>=s.hpMax:s.player.stamina>=s.staminaMax)result='Already full.';else{p.potions[id]--;if(id==='health')s.player.hp=Math.min(s.hpMax,s.player.hp+supplies.health.restore);else s.player.stamina=Math.min(s.staminaMax,s.player.stamina+supplies.stamina.restore);result='Supply used.';this.persist();}this.render();this.detail.querySelector('#supply-status')!.textContent=result;};
  const assign=this.detail.querySelector<HTMLButtonElement>('#assign-supply');if(assign)assign.onclick=()=>{const i=Number(this.detail.querySelector<HTMLSelectElement>('#pocket-select')!.value);p.pockets=p.pockets.map(v=>v===this.item?null:v);p.pockets[i]=this.item;this.slot=i;this.persist();this.render();};
  const clear=this.detail.querySelector<HTMLButtonElement>('#clear-pocket');if(clear)clear.onclick=()=>{p.pockets[Number(this.detail.querySelector<HTMLSelectElement>('#pocket-select')!.value)]=null;this.persist();this.render();};
  this.detail.querySelectorAll<HTMLButtonElement>('[data-skill]').forEach(b=>b.onclick=()=>this.editArts(b.dataset.skill));
  this.detail.querySelectorAll<HTMLButtonElement>('[data-chat]').forEach(b=>b.onclick=()=>{const id=b.dataset.chat!;if(!p.chats.includes(id))p.chats.push(id);this.persist();this.detail.querySelector('#chat-history')!.innerHTML=p.chats.map(id=>this.chat(id)).join('');});
  this.branch.querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.dataset.category===this.category));
 }
 private chat(id:string){return '<p><b>Ilyra:</b> '+(id==='guild'?'The Guild Hall is a place to meet and prepare. Touch the Training Room orb to begin combat practice, or leave when you are ready.':'Basic Arts work with every weapon and use its original base damage. Combat Arts may require a weapon or class. Skill Books collect themed Combat Arts into branching trees with unlock requirements. The future tutorial dungeon will award a small starter book.')+'</p>';}
 private equipment(){const w=this.sim.weaponDefinition;return [['Head','Empty','No head equipment owned.'],['Right hand',w.name,w.description+' Change weapons at the physical rack.'],['Left hand',w.id==='greatsword'?'Two-handed grip':'Empty',w.id==='greatsword'?'Reserved by your two-handed sword.':'No off-hand equipment owned.'],['Body','Training uniform','Equipped starter clothing. Cosmetic; no armor bonus.'],['Feet','Training boots','Equipped starter boots. Cosmetic; no movement bonus.']];}
 update(){const s=this.sim,p=s.profile;this.panel.querySelector('#personal-character-name')!.textContent=p.name;const cell=Math.max(-3,Math.min(3,Math.round(s.player.x/4)))+','+Math.max(-3,Math.min(3,Math.round(s.player.z/4)));if(!p.explored.includes(cell))p.explored.push(cell);if(s.enemies.some(e=>e.species!=='boar'))p.sentinelSeen=true;if(s.enemies.some(e=>e.species==='boar'))p.boarSeen=true;
  this.panel.querySelector('#personal-weapon')!.textContent=s.weaponDefinition.name;this.panel.querySelector('#personal-weapon-stats')!.textContent=Math.round(physicalDamage(s.weaponDefinition.damage,s.attributes.strength))+' damage · '+s.weaponDefinition.shape.range+' m reach';
  this.panel.querySelectorAll<HTMLButtonElement>('[data-pocket]').forEach((b,i)=>{const id=p.pockets[i];b.textContent=id?(id==='health'?'HP':'STA')+' ×'+p.potions[id as 'health']:'+';b.title=id?(supplies[id as 'health'].name):'Empty inventory slot';});
  const sig=[s.weapon,s.attributes.strength,s.progression.tutorialCompleted,s.progression.completed.join(','),Object.keys(s.progression.learned).join(','),p.sentinelSeen,p.boarSeen,s.loadout.join(),this.category==='map'?p.explored.join(';'):'',this.category==='manual'?s.counters.kills:0,this.category==='manual'?s.counters.parries:0].join('|');if(this.signature!==sig){this.signature=sig;if(!this.detail.hidden)this.render();}
  const dot=this.detail.querySelector('#map-player');if(dot){dot.setAttribute('cx',String(140+s.player.x*8));dot.setAttribute('cy',String(140-s.player.z*8));}
 }
}
