import {artIcon,menuIcon} from './artIcon';
import {lootItems,type LootItem} from '../data/creatureLoot';
import {weapons} from '../data/weapons';
import {publicUrl} from '../publicUrl';
import {cavernAreas as chambers,cavernLinks} from '../world/cavern';
import {supplies} from '../data/items';
import {bookLibrary,bindBookLibrary} from './skillBooks';
import type {CombatSimulation} from '../combat/simulation';
import {arts} from '../data/arts';
import {physicalDamage} from '../data/balance';


export class PersonalMenu {
 panel=document.createElement('section');detail=document.createElement('section');branch=document.createElement('nav');
 private resourceSignature='';private category='items';private signature='';private slot=0;private item='health';
 constructor(private sim:CombatSimulation,private editArts:(id?:string)=>void,private persist:()=>void){
  this.panel.id='personal-artifact';this.panel.setAttribute('aria-label','Character equipment');
  this.panel.innerHTML=`<div class="artifact-title"><span id="personal-character-name"></span><small>CHARACTER / EQUIPMENT</small></div>
  <div id="personal-resources"></div><div class="equipment-body"><svg viewBox="0 0 260 280" role="img" aria-label="Character silhouette"><ellipse cx="130" cy="252" rx="43" ry="5" fill="#526169" opacity=".18"/><g class="body-silhouette"><circle cx="130" cy="65" r="13"/><path d="M116 82 Q130 77 144 82 L155 132 151 159 142 131 142 165 155 245 137 245 130 188 123 245 105 245 118 165 118 131 109 159 105 132Z"/></g></svg>
  ${['Head','Right hand','Left hand','Body','Feet'].map((name,i)=>`<button class="body-slot body-slot-${i}" data-equipment="${i}" title="${name}" aria-label="Inspect ${name}"><i>◇</i><span>${name}</span></button>`).join('')}</div>
  <div id="personal-attributes"></div><div class="pocket-label">QUICK INVENTORY</div><div class="pocket-row">${[0,1,2,3,4].map(i=>`<button data-pocket="${i}" aria-label="Inventory slot ${i+1}"></button>`).join('')}</div><div class="equipment-description"><small>EQUIPPED WEAPON</small><h2 id="personal-weapon"></h2><p id="personal-weapon-stats"></p><small>Equip recovered blades in Items, or visit the rack.</small></div><div id="personal-record"></div>`;
  this.detail.id='personal-detail';this.detail.setAttribute('aria-label','Personal information');this.branch.id='character-branch';
  this.branch.setAttribute('aria-label','Personal menu navigation');
  this.branch.innerHTML=[['character-menu','items','Items'],['skills-menu','arts','Skills'],['equipment-menu','equipment','Equipment'],['friends-menu','friends','Friends'],['map-menu','map','Map'],['manual-menu','manual','Bestiary']].map(([id,category,label])=>`<button id="${id}" data-category="${category}" aria-label="${label}"><i>${menuIcon(category)}</i><span>${label}</span></button>`).join('');
  document.querySelector('#ui')!.append(this.panel,this.branch,this.detail);
  this.panel.querySelectorAll<HTMLButtonElement>('[data-equipment]').forEach(b=>b.onclick=()=>{this.open('equipment');this.detail.querySelectorAll<HTMLDetailsElement>('details')[Number(b.dataset.equipment)]!.open=true;});
  this.panel.querySelectorAll<HTMLButtonElement>('[data-pocket]').forEach(b=>b.onclick=()=>{this.slot=Number(b.dataset.pocket);this.item=sim.profile.pockets[this.slot]??'health';this.open('items');});
  this.branch.querySelectorAll<HTMLButtonElement>('[data-category]').forEach(b=>b.onclick=()=>this.open(b.dataset.category!));
  this.open('items');
 }
 private heading(title:string){return `<div class="personal-detail-heading"><h2>${title}</h2><button id="personal-detail-close" aria-label="Close information">×</button></div>`;}
 open(category:string){this.category=category;this.detail.hidden=false;this.branch.classList.add('expanded');const tray=document.getElementById('loadout-tray');if(tray)tray.hidden=true;this.render();}
 private render(){
  const s=this.sim,p=s.profile;let html='';
  if(this.category==='items'){
   html=this.heading('Items')+`<p class="subtle">${s.journey.coins} Col · carried supplies.</p><div class="inventory-list">${['health','stamina'].map(id=>`<button data-item="${id}" aria-pressed="${this.item===id}">${supplies[id as 'health'].name} <b>×${p.potions[id as 'health']}</b></button>`).join('')}</div><article><h3>${supplies[this.item as 'health'].name}</h3><p>Restores ${this.item==='health'?supplies.health.restore+' HP':supplies.stamina.restore+' stamina'}. Consumed on use. Usable while exploring or fighting, between actions. Supplies share a 5-second cooldown; unavailable during guided lessons.</p><button id="use-supply">Use supply</button><p id="supply-status" role="status"></p><label>Accessible inventory slot<select id="pocket-select">${p.pockets.map((_,i)=>`<option value="${i}" ${this.slot===i?'selected':''}>Slot ${i+1}</option>`).join('')}</select></label><button id="assign-supply">Assign here</button><button id="clear-pocket">Clear slot</button></article>`;
   html+=`<h3>Carried weapons</h3><button id="equip-starting-weapon">Equip starting ${weapons[s.journey.startingWeapon]?.name??'sword'}</button>${(['dagger','cleaver'] as const).map(id=>{const w=weapons[id];return `<details class="nested-info"><summary>${w.name} <small>×${s.journey.items[id]}</small></summary><p>${w.description}</p><p>${w.damage} base damage · ${w.break} Break · ${w.shape.range} m reach · ${w.startup} ms wind-up / ${w.recovery} ms recovery.</p><p>Source: ${lootItems[id].source}.</p><button id="equip-loot-${id}" data-loot-weapon="${id}" ${s.journey.items[id]?'':'disabled'}>${s.weapon===id?'Equipped':'Equip '+w.name}</button></details>`;}).join('')}<h3>Materials & keepsakes</h3>${(['scrapIron','leatherScraps','hide','token'] as const).filter(id=>s.journey.items[id]>0).map(id=>`<details class="nested-info" data-material="${id}"><summary>${lootItems[id].name} <small>×${s.journey.items[id]}</small></summary><p>${lootItems[id].use}</p><p>Source: ${lootItems[id].source}.</p></details>`).join('')||'<p>No materials collected yet.</p>'}`;
  }else if(this.category==='arts')html=this.heading('Skills')+`<p class="subtle">Basic Arts work with any weapon. Combat Arts may require a weapon or class. Skill Books open themed trees. Select a skill to inspect and equip it.</p><div class="skill-name-list">${Object.values(arts).filter(a=>s.progression.learned[a.id]).map(a=>`<button data-skill="${a.id}">${artIcon(a.id)}<span>${a.name}</span><small>${s.loadout.includes(a.id)?'Equipped · '+(s.loadout.indexOf(a.id)+1):'View details'} ›</small></button>`).join('')}</div>${bookLibrary(s)}<a href="${publicUrl('/data/skill-bank.json')}" download>Download skill bank</a>`;
  else if(this.category==='equipment')html=this.heading('Equipment')+this.equipment().map(([slot,name,desc])=>`<details class="nested-info"><summary>${slot}<small>${name}</small></summary><p>${desc}</p></details>`).join('');
  else if(this.category==='friends'){
   const done=s.progression.tutorialCompleted;
   html=this.heading('Friends')+(s.journey.facts.includes('mira')?'<details class="nested-info" open><summary>Mira Vale<small>Town wayfinder</small></summary><p>Location: Town of Beginnings · Lower Gate Square.</p><h3>Current quest · Beyond the First Gate</h3><p>Bring the captain’s brass token to the eastern watch. The next expedition is not yet open.</p><details><summary>Completed quests</summary><p>Under-town incursion cleared. Any accepted quest reward is recorded in your Skill Books.</p></details><details><summary>Conversation</summary><p>Mira thanked your party. Goblins used an old drain from outside town. Their crown-and-three-spears token suggests an organized threat beyond the walls.</p></details></details>':'')+'<p>Guild contact</p><details class="nested-info" open><summary>Warden Ilyra<small>Guild mentor · NPC</small></summary><p>Ilyra prepares new adventurers for the roads beyond town.</p><p>Location: Guild Hall · Town of Beginnings · Floor 1.</p><h3>Current quests</h3>'+(done?'<p>No open quests.</p>':'<article><h4>Guild Combat Trial</h4><p>Touch the entrance orb in the Training Room. Learn targeting, movement, basic attacks, dodging, countering and Combat Arts.</p><p>Reward: Linear — Perfect dashes 6 m through a target; Good deals 60% damage and travels 1 m.</p></article>')+'<details class="nested-info"><summary>Completed quests · '+(done?'1':'0')+'</summary>'+(done?'<p>✓ Guild Combat Trial</p><p>Learned Linear by completing Ilyra’s combat induction.</p>':'<p>No completed quests yet.</p>')+'</details><details><summary>Chats with Ilyra</summary><button data-chat="guild">What is the Lantern Guild?</button><button data-chat="oath">What are Skill Books?</button><div id="chat-history">'+p.chats.map(id=>this.chat(id)).join('')+'</div></details></details>';
  }else if(this.category==='map')html=this.heading('Floor 1 · Known map')+`<p>Current location: ${s.journey.active?chambers[s.journey.room].name:'Training Room'}</p><p>${s.journey.active?'Explored route: '+chambers.slice(0,s.journey.room+1).map(r=>r.name).join(' → '):'Guild Hall · Training Room'}. The wider town and outer roads are not yet open.</p><svg class="floor-map" viewBox="0 0 280 280" role="img" aria-label="Explored training room map"><rect width="280" height="280" fill="#5b6b6c"/>${p.explored.map(v=>{const [x,z]=v.split(',').map(Number);return `<rect x="${140+x*32-16}" y="${140-z*32-16}" width="32" height="32" fill="#dbe5dd" stroke="#bac8c2"/>`;}).join('')}<circle cx="140" cy="140" r="110" fill="none" stroke="#f1e4ae"/><rect x="71" y="63" width="10" height="10" fill="#d7b94d"/><circle id="map-player" cx="${140+s.player.x*8}" cy="${140-s.player.z*8}" r="5" fill="#208db3"/></svg><p>Blue: you · Gold: known weapon rack · Dark: unexplored</p>`;
  else html=this.heading('Monster manual')+(p.sentinelSeen?`<details class="nested-info" open><summary>Aether Sentinel<small>Training construct · encountered</small></summary><p>Found in the Training Room during lessons and trials.</p><p>Read the weapon animation for basic attacks. Gold warnings can be countered; red sweeps require a dodge. Fill Break to create an opening. Rear weak point: +20% damage within the rear 120° arc. Use Linear to pass its committed attack; it must turn before attacking again.</p><p>Recorded victories: ${s.counters.kills} · Perfect counters: ${s.counters.parries}</p></details>`:p.boarSeen?'':'<p>No creatures recorded. Begin a lesson or Guild challenge to encounter a training construct.</p>');
      if(this.category==='map'&&s.journey.active)html=this.heading('Discovered cavern')+`<p>${chambers[s.journey.room].name}</p><svg class="floor-map" viewBox="-65 -20 130 200" role="img" aria-label="Discovered cavern passages"><rect x="-65" y="-20" width="130" height="200" fill="#34484d"/>${cavernLinks.filter(([a,b])=>s.journey.visited.includes(a)&&s.journey.visited.includes(b)).map(([a,b])=>`<path d="M${chambers[a].x} ${160-chambers[a].z} L${chambers[b].x} ${160-chambers[b].z}" stroke="#92aaa5" stroke-width="5"/>`).join('')}${s.journey.visited.map(i=>`<circle cx="${chambers[i].x}" cy="${160-chambers[i].z}" r="${chambers[i].radius}" fill="#bfd0c4"><title>${chambers[i].name}</title></circle>`).join('')}<circle id="cavern-map-player" cx="${s.player.x}" cy="${160-s.player.z}" r="2" fill="#ebad19"/></svg><p>Gold: you. Only discovered spaces are shown.</p>`;


 if(this.category==='friends'&&s.journey.active&&!s.journey.facts.includes('mira'))html=this.heading('Friends')+'<p>No contacts yet. Reach town to meet your first guide.</p>';
  if(this.category==='manual'&&(s.journey.room>0||s.journey.cleared.includes(1)))html+=`<details class="nested-info" open><summary>Goblin Sentry<small>Under-town incursion</small></summary><p>Basic scrap-blade chops can be countered; red sweeps must be dodged. Their weapons commit before impact, giving you time to move behind them. Rear hits deal +20% damage. Health varies by patrol.</p><p>The captain reveals a two-cut gold attack below half health. Watch both beats, or leave the attack area.</p></details>`;
  if(this.category==='manual'&&p.boarSeen)html+=`<details class="nested-info" open><summary>Woodland Boar<small>Training beast · encountered</small></summary><p>220 HP. A quick tusk jab can be countered. Its wider, red head sweep must be dodged. Punish the long recovery. Rear weak point: +20% damage within the rear 120° arc; its slow turn gives you time to reposition.</p></details>`;this.detail.innerHTML=html;bindBookLibrary(this.detail,s,()=>{this.persist();this.render();});this.detail.querySelector<HTMLButtonElement>('#personal-detail-close')!.onclick=()=>this.detail.hidden=true;
  this.detail.querySelectorAll<HTMLButtonElement>('[data-item]').forEach(b=>b.onclick=()=>{this.item=b.dataset.item!;this.render();});
  const starting=this.detail.querySelector<HTMLButtonElement>('#equip-starting-weapon');if(starting)starting.onclick=()=>{if(s.setWeapon(s.journey.startingWeapon)){this.persist();this.render();}};
  this.detail.querySelectorAll<HTMLButtonElement>('[data-loot-weapon]').forEach(b=>b.onclick=()=>{const id=b.dataset.lootWeapon as LootItem;if(s.journey.items[id]&&s.setWeapon(id)){this.persist();this.render();}});
  const use=this.detail.querySelector<HTMLButtonElement>('#use-supply');if(use)use.onclick=()=>{const result=s.useSupply(this.item as 'health'|'stamina');if(result.used)this.persist();this.render();this.detail.querySelector('#supply-status')!.textContent=result.message;};
  const assign=this.detail.querySelector<HTMLButtonElement>('#assign-supply');if(assign)assign.onclick=()=>{const i=Number(this.detail.querySelector<HTMLSelectElement>('#pocket-select')!.value);p.pockets=p.pockets.map(v=>v===this.item?null:v);p.pockets[i]=this.item;this.slot=i;this.persist();this.render();};
  const clear=this.detail.querySelector<HTMLButtonElement>('#clear-pocket');if(clear)clear.onclick=()=>{p.pockets[Number(this.detail.querySelector<HTMLSelectElement>('#pocket-select')!.value)]=null;this.persist();this.render();};
  this.detail.querySelectorAll<HTMLButtonElement>('[data-skill]').forEach(b=>b.onclick=()=>this.editArts(b.dataset.skill));
  this.detail.querySelectorAll<HTMLButtonElement>('[data-chat]').forEach(b=>b.onclick=()=>{const id=b.dataset.chat!;if(!p.chats.includes(id))p.chats.push(id);this.persist();this.detail.querySelector('#chat-history')!.innerHTML=p.chats.map(id=>this.chat(id)).join('');});
  this.branch.querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.dataset.category===this.category));
 }
 private chat(id:string){return '<p><b>Ilyra:</b> '+(id==='guild'?'The Guild Hall is a place to meet and prepare. Touch the Training Room orb to begin combat practice, or leave when you are ready.':'Basic Arts work with every weapon and use its original base damage. Combat Arts may require a weapon or class. Skill Books collect themed Combat Arts into branching trees with unlock requirements. Clear the under-town prologue to choose a small starter book.')+'</p>';}
 private equipment(){const w=this.sim.weaponDefinition;return [['Head','Empty','No head equipment owned.'],['Right hand',w.name,w.description+' Change weapons at the rack or equip recovered weapons from Items.'],['Left hand',w.id==='greatsword'?'Two-handed grip':'Empty',w.id==='greatsword'?'Reserved by your two-handed sword.':'No off-hand equipment owned.'],['Body','Training uniform','Equipped starter clothing. Cosmetic; no armor bonus.'],['Feet','Training boots','Equipped starter boots. Cosmetic; no movement bonus.']];}
 update(){const s=this.sim,p=s.profile;this.panel.querySelector('#personal-character-name')!.textContent=p.name;const cell=Math.max(-3,Math.min(3,Math.round(s.player.x/4)))+','+Math.max(-3,Math.min(3,Math.round(s.player.z/4)));if(!p.explored.includes(cell))p.explored.push(cell);if(s.enemies.some(e=>e.species==='sentinel'))p.sentinelSeen=true;if(s.enemies.some(e=>e.species==='boar'))p.boarSeen=true;
  const resourceSignature=[Math.ceil(s.player.hp),s.hpMax,Math.ceil(s.player.stamina),s.staminaMax,s.player.sp,...Object.values(s.attributes),s.journey.coins,s.journey.room,s.journey.active,Math.floor(s.journey.elapsedMs/60000)].join('|');if(resourceSignature!==this.resourceSignature){this.resourceSignature=resourceSignature;this.panel.querySelector('#personal-resources')!.innerHTML=[['HP',s.player.hp,s.hpMax,'hp'],['Stamina',s.player.stamina,s.staminaMax,'sta'],['SP',s.player.sp,100,'sp']].map(([label,value,max,id])=>`<div class="journal-resource"><span>${label}</span><i><b class="journal-fill-${id}" style="width:${Math.max(0,Math.min(100,Number(value)/Number(max)*100))}%"></b></i><small>${Math.ceil(Number(value))} / ${max}</small></div>`).join('');
  this.panel.querySelector('#personal-attributes')!.innerHTML=[['STR',s.attributes.strength],['DEX',s.attributes.dexterity],['VIT',s.attributes.vitality],['END',s.attributes.endurance]].map(([label,n])=>`<span>${label}<b>${n}</b></span>`).join('');
  this.panel.querySelector('#personal-record')!.innerHTML=`<div><span>Col</span><b>${s.journey.coins.toLocaleString()}</b></div><div><span>Location</span><b>${s.journey.active?chambers[s.journey.room].name:'Training Room'}</b></div><div><span>Play time</span><b>${Math.floor(s.journey.elapsedMs/3600000)}:${String(Math.floor(s.journey.elapsedMs/60000)%60).padStart(2,'0')}</b></div>`;
}
  this.panel.querySelector('#personal-weapon')!.textContent=s.weaponDefinition.name;this.panel.querySelector('#personal-weapon-stats')!.textContent=Math.round(physicalDamage(s.weaponDefinition.damage,s.attributes.strength))+' damage · '+s.weaponDefinition.shape.range+' m reach';
  this.panel.querySelectorAll<HTMLButtonElement>('[data-pocket]').forEach((b,i)=>{const id=p.pockets[i];b.textContent=id?(id==='health'?'HP':'STA')+' ×'+p.potions[id as 'health']:'+';b.title=id?(supplies[id as 'health'].name):'Empty inventory slot';});
  const sig=[...Object.values(s.journey.items),p.potions.health,p.potions.stamina,s.journey.coins,s.journey.room,s.journey.book,s.journey.leafLearned,s.journey.facts.join(),s.weapon,s.attributes.strength,s.progression.tutorialCompleted,s.progression.completed.join(','),Object.keys(s.progression.learned).join(','),p.sentinelSeen,p.boarSeen,s.loadout.join(),this.category==='map'?p.explored.join(';'):'',this.category==='manual'?s.counters.kills:0,this.category==='manual'?s.counters.parries:0].join('|');if(this.signature!==sig){this.signature=sig;if(!this.detail.hidden)this.render();}
  const caveDot=this.detail.querySelector('#cavern-map-player');if(caveDot){caveDot.setAttribute('cx',String(s.player.x));caveDot.setAttribute('cy',String(160-s.player.z));}
  const dot=this.detail.querySelector('#map-player');if(dot){dot.setAttribute('cx',String(140+s.player.x*8));dot.setAttribute('cy',String(140-s.player.z*8));}
 }
}