import type {CombatAudio} from '../audio/audio';
import type {Comfort} from '../settings';
import type {SaveData} from '../save/save';
import {backupText,parseBackup,downloadText,replaceWithBackup,previousBackup} from '../save/backup';
import {buildId} from '../release';
export function playtestSettings(audio:CombatAudio,comfort:Comfort,apply:()=>void,persist:()=>Promise<void>,read:()=>Promise<SaveData>,beginImport:()=>void,endImport:()=>void,diagnostics:()=>unknown){
 const panel=document.createElement('details');panel.className='system-preferences';panel.id='playtest-settings';
 panel.innerHTML=`<summary>Comfort, calibration & saves</summary><p>${buildId} · Desktop combat playtest</p><label>Cue volume <input id="cue-volume" type="range" min="0" max="1" step=".05"></label><label>Impact volume <input id="effects-volume" type="range" min="0" max="1" step=".05"></label><label>Play cues earlier (ms) <input id="cue-offset" type="number" min="-200" max="200" step="5"></label><p>Positive offset plays audio earlier. Hit timing stays unchanged. Negative plays later.</p><label><input id="reduced-motion" type="checkbox"> Reduce camera shake</label><label><input id="reduced-flash" type="checkbox"> Reduce flashes and particles</label><button id="calibrate-audio">Start eight-beat calibration</button><button id="calibration-tap" disabled>Tap with each beat</button><p id="calibration-status" role="status">Use headphones if possible. Tap the button or Space with the beat; the first two beats are practice.</p><hr><button id="export-save">Download save backup</button><label>Preview backup to import <input id="import-save" type="file" accept="application/json,.json"></label><button id="apply-import" disabled>Replace progress with previewed backup</button><button id="previous-save">Download pre-import recovery backup</button><button id="export-diagnostics">Download anonymous diagnostics</button><p id="save-tools-status" role="status">Imports keep a recovery backup. Diagnostics download locally; nothing is uploaded.</p>`;
 document.querySelector('.intro')!.append(panel);const el=<T extends HTMLElement>(id:string)=>panel.querySelector<T>('#'+id)!;
 const status=(text:string)=>el('save-tools-status').textContent=text;
 for(const [id,key] of [['cue-volume','cueVolume'],['effects-volume','effectsVolume'],['cue-offset','cueOffsetMs']] as const){const input=el<HTMLInputElement>(id);input.value=String(comfort[key]);input.oninput=()=>{const n=Number(input.value);if(!Number.isFinite(n))return;comfort[key]=Math.max(Number(input.min),Math.min(Number(input.max),n));apply();void persist();};}
 for(const [id,key] of [['reduced-motion','reducedMotion'],['reduced-flash','reducedFlash']] as const){const input=el<HTMLInputElement>(id);input.checked=comfort[key];input.onchange=()=>{comfort[key]=input.checked;apply();void persist();};}
 let pending:SaveData|undefined;
 el<HTMLInputElement>('import-save').onchange=async()=>{pending=undefined;el<HTMLButtonElement>('apply-import').disabled=true;try{const file=el<HTMLInputElement>('import-save').files?.[0];if(!file)return;if(file.size>1_000_000)throw Error('Backup too large');pending=parseBackup(await file.text());status(`Preview: ${pending.profile.name} · ${pending.weapon} · ${Object.keys(pending.progression.learned).length} learned Arts. Apply to replace current progress.`);el<HTMLButtonElement>('apply-import').disabled=false;}catch(error){status('Import rejected: '+String(error));}};
 el('apply-import').onclick=async()=>{if(!pending)return;el<HTMLButtonElement>('apply-import').disabled=true;try{await persist();beginImport();await replaceWithBackup(pending);location.reload();}catch(error){endImport();status('Import failed; current save retained. '+String(error));}};
 el('export-save').onclick=async()=>{try{await persist();downloadText('trinity-save.json',backupText(await read()));status('Save backup downloaded.');}catch(error){status('Could not export: '+String(error));}};
 el('previous-save').onclick=async()=>{try{const old=await previousBackup();if(!old){status('No import recovery backup yet.');return;}downloadText('trinity-recovery.json',backupText(old));status('Recovery backup downloaded; preview it above to restore.');}catch(error){status(String(error));}};
 el('export-diagnostics').onclick=()=>{downloadText('trinity-diagnostics.json',JSON.stringify({buildId,...diagnostics() as object},null,2));status('Diagnostics downloaded locally. Share it with your feedback if you choose.');};
 let nodes:OscillatorNode[]=[],endTimer:ReturnType<typeof setTimeout>|undefined,beats:number[]=[],offsets:number[]=[],lastBeat=-1;
 const stop=()=>{for(const n of nodes){try{n.stop();}catch{/* ended */}}nodes=[];clearTimeout(endTimer);el<HTMLButtonElement>('calibration-tap').disabled=true;};
 el('calibrate-audio').onclick=()=>{stop();audio.unlock();const ctx=audio.context!;beats=[];offsets=[];lastBeat=-1;for(let i=0;i<8;i++){const when=ctx.currentTime+1+i*.6,osc=ctx.createOscillator(),gain=ctx.createGain();beats.push(when);osc.frequency.value=i===7?880:440;gain.gain.setValueAtTime(.08*comfort.cueVolume,when);gain.gain.exponentialRampToValueAtTime(.0001,when+.12);osc.connect(gain);gain.connect(ctx.destination);osc.start(when);osc.stop(when+.13);osc.onended=()=>{osc.disconnect();gain.disconnect();};nodes.push(osc);}el<HTMLButtonElement>('calibration-tap').disabled=false;el('calibration-tap').focus();el('calibration-status').textContent='Tap in rhythm; first two beats do not count.';endTimer=setTimeout(()=>{stop();if(offsets.length<4){el('calibration-status').textContent='Not enough taps. Try again; you need four measured beats.';return;}offsets.sort((a,b)=>a-b);comfort.cueOffsetMs=Math.max(-200,Math.min(200,Math.round(offsets[Math.floor(offsets.length/2)]/5)*5));el<HTMLInputElement>('cue-offset').value=String(comfort.cueOffsetMs);apply();void persist();el('calibration-status').textContent=`Suggested offset: ${comfort.cueOffsetMs} ms. Includes your tap response; fine-tune above if it feels wrong.`;},5800);};
 el('calibration-tap').onclick=()=>{const now=audio.context?.currentTime??0;let best=0;for(let i=1;i<beats.length;i++)if(Math.abs(beats[i]-now)<Math.abs(beats[best]-now))best=i;if(best<=lastBeat||Math.abs(beats[best]-now)>.25)return;lastBeat=best;if(best>=2)offsets.push((now-beats[best])*1000);el('calibration-status').textContent=`Beat ${best+1}/8 · ${offsets.length} measured taps`;};
 panel.addEventListener('keydown',e=>{if(e.code==='Space'&&(e.target as HTMLElement).id==='calibration-tap'){e.preventDefault();e.stopPropagation();if(!el<HTMLButtonElement>('calibration-tap').disabled)el('calibration-tap').click();}});
  window.addEventListener('trinity-audio-stop',stop);window.addEventListener('blur',stop);document.getElementById('begin')!.addEventListener('click',stop);panel.addEventListener('toggle',()=>{if(!panel.open)stop();});
}
