import {primers,canLearnLeaf,primerArts} from '../world/journey';
import {arts} from '../data/arts';
import type {CombatSimulation} from '../combat/simulation';
import {skillCard} from './skillCard';
export function bookLibrary(sim:CombatSimulation){return `<details class="nested-info" id="skill-books"><summary>Skill Books <small>Three small, weapon-neutral trees</small></summary><p>Accept Find an exit, defeat the under-town captain and speak to Mira to choose one primer. The first node is learned immediately; the second requires practice after receiving the book. No class restriction. These are modest utility forms, not replacements for weapon-specialized Arts.</p>${primers.map(book=>`<article class="book-preview"><h3>${book.name}</h3><small>${sim.journey.book===book.id?'OWNED':'NOT OWNED'} · TWO NODES</small><p>${book.theme}</p><div class="skill-name-list">${[book.root,book.leaf].map(id=>`<button data-book-node="${id}">${arts[id].name}<small>${sim.progression.learned[id]?'Learned':'Locked'} ›</small></button>`).join('')}</div><div class="book-node-detail" aria-live="polite">Select a node for details and requirements.</div></article>`).join('')}</details>`;}
export function bindBookLibrary(root:HTMLElement,sim:CombatSimulation,persist:()=>void=()=>{}){root.querySelectorAll<HTMLButtonElement>('[data-book-node]').forEach(b=>b.onclick=()=>{
 const book=primers.find(p=>p.root===b.dataset.bookNode||p.leaf===b.dataset.bookNode)!,id=b.dataset.bookNode!,owned=sim.journey.book===book.id,leaf=id===book.leaf,known=!!sim.progression.learned[id];
 const panel=b.closest('.book-preview')!.querySelector<HTMLElement>('.book-node-detail')!;
 panel.innerHTML=`<h3>${arts[id].name}</h3><p>${known?'Learned':owned?'Owned book · node locked':'Complete the accepted Find an exit quest to choose this Book.'}</p>${leaf?`<p>${book.requirement}</p><p>Since acquisition: ${sim.journey.practice.hits} basics · ${sim.journey.practice.evades} evades · ${sim.journey.practice.parries} Counters · ${sim.journey.practice.breaks} Breaks.</p>`:''}${skillCard(primerArts[id],sim)}${owned&&leaf&&!known?`<button id="learn-book-node" ${canLearnLeaf(sim.journey)?'':'disabled'}>Learn ${arts[id].name}</button>`:''}`;
 const learn=panel.querySelector<HTMLButtonElement>('#learn-book-node');if(learn)learn.onclick=()=>{if(sim.gmMode||!owned||!canLearnLeaf(sim.journey))return;sim.journey.leafLearned=true;sim.progression.learned[id]='skill book';persist();};
 });}
