import {artShape,chargeDuration,type ArtDefinition} from '../data/arts';
import {balance,physicalDamage} from '../data/balance';
import type {CombatSimulation} from '../combat/simulation';
export function skillCard(def:ArtDefinition,sim:CombatSimulation){
 const a=structuredClone(def);if(a.id==='crescent-break'){if(sim.progression.masteryChoice==='break'){a.nodes.forEach(n=>n.break*=1.35);a.recovery=460;}if(sim.progression.masteryChoice==='recovery')a.recovery=200;}
 const damage=a.nodes.reduce((n,h)=>n+Math.round(physicalDamage(h.multiplier*sim.weaponDefinition.damage,sim.attributes.strength)),0),br=a.nodes.reduce((n,h)=>n+h.break,0),range=artShape(a).range,travel=Math.hypot(a.movement,a.sideMovement??0),goodTravel=Math.hypot(a.goodMovement??a.movement,a.sideMovement??0);
 const scores=[Math.min(1,damage/175),Math.min(1,range/6),Math.min(1,travel/6),Math.min(1,br/100),Math.max(0,1-a.recovery/1000),Math.max(0,1-a.cost/100)],labels=['Damage','Reach','Travel','Break','Recovery','SP economy'];
 const point=(i:number,r:number)=>[110+Math.sin(i*Math.PI/3)*r,100-Math.cos(i*Math.PI/3)*r];
 const poly=(r:number)=>scores.map((_,i)=>point(i,r).join(',')).join(' ');
 const radar=`<svg class="skill-radar" viewBox="0 0 220 210" role="img" aria-label="${a.name} relative stat profile">${[20,40,60].map(r=>`<polygon points="${poly(r)}" class="radar-grid"/>`).join('')}<polygon points="${scores.map((v,i)=>point(i,v*60).join(',')).join(' ')}" class="radar-fill"/>${labels.map((label,i)=>{const [x,y]=point(i,85);return `<text x="${x}" y="${y}" text-anchor="middle">${label}</text>`;}).join('')}</svg>`;
 const shape=artShape(a),footprint=shape.kind==='box'?`${shape.range} m × ${shape.halfWidth*2} m lane`:shape.kind==='sector'?`${shape.range} m / ${Math.round(shape.halfArc*360/Math.PI)}° fan`:`${shape.range} m circle`;
 return `<details class="nested-info skill-card"><summary>${a.name}<small>${a.cost} SP · ${a.nodes.length} event${a.nodes.length>1?'s':''} · ${a.weapon==='any'?'All training weapons':a.weapon}</small></summary><p>${a.description}</p><div class="skill-profile">${radar}<dl><dt>Art tier</dt><dd>${a.weapon==='any'?'Foundation · general weapon':'Specialist · restricted weapon'}</dd><dt>Weapon scaling</dt><dd>${a.nodes.map(n=>n.multiplier+'×').join(' + ')} weapon base (${sim.weaponDefinition.damage})</dd><dt>Perfect damage</dt><dd>${damage}</dd><dt>Good damage</dt><dd>${a.nodes.reduce((n,h)=>n+Math.round(physicalDamage(h.multiplier*sim.weaponDefinition.damage*.6,sim.attributes.strength)),0)}</dd><dt>Break · Perfect / Good</dt><dd>${br.toFixed(0)} / ${(br*.6).toFixed(0)}</dd><dt>Travel · Perfect / Good</dt><dd>${travel.toFixed(2)} / ${goodTravel.toFixed(2)} m${a.sideMovement?' sideways':''}</dd><dt>Hit area</dt><dd>${footprint}</dd><dt>Targets</dt><dd>${a.maxTargets??'All in area'}</dd><dt>Hold target</dt><dd>${a.nodes.map((_,i)=>chargeDuration(a,i)+' ms').join(' → ')}</dd><dt>Perfect window</dt><dd>±${balance.timing.perfect} ms</dd><dt>Good window</dt><dd>±${balance.timing.good} ms, outside Perfect</dd><dt>Swing / recovery</dt><dd>${a.startup} / ${a.recovery} ms</dd><dt>Interruption protection</dt><dd>${a.armor?'Nonlethal hits':'None'}</dd>${a.restoreStamina?`<dt>Stamina on hit</dt><dd>${a.restoreStamina} Perfect / ${a.restoreStamina*.6} Good</dd>`:''}</dl></div><small>Damage = weapon base × Art multiplier × Strength scaling × timing grade. Radar scales: 175 damage, 6 m reach/travel, 100 Break; recovery/SP economy increase as cost falls. Arena edges may shorten travel.</small><p>Hold the assigned Art button and release on the cue.${a.nodes.length>1?' After contact, hold and release again.':''} Miss: no new hit, SP spent.</p></details>`;
}
