import {skillBooks,bookRequirements} from '../data/skillBooks';
import {arts} from '../data/arts';
import type {CombatSimulation} from '../combat/simulation';
import {skillCard} from './skillCard';
export function bookLibrary(sim:CombatSimulation){return `<details class="nested-info" id="skill-books"><summary>Skill Books <small>Themed skill trees · preview a future dungeon reward</small></summary><p>A Skill Book opens a family of related skills. Small primers have a few nodes; larger volumes can have branching specializations. Owning a book opens its tree, but deeper nodes can require earlier forms, practice milestones or quests. A skill already learned elsewhere stays learned.</p>${skillBooks.map(book=>`<article class="book-preview"><h3>${book.name}</h3><small>SMALL PRIMER · ${book.nodes.length} NODES · NOT OWNED</small><p>${book.theme}</p><p>${book.reward}</p><div class="book-tree" aria-label="${book.name} skill tree"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${book.nodes.flatMap(n=>n.parents.map(id=>{const from=book.nodes.find(p=>p.art===id)!;return `<line x1="${from.x}" y1="${from.y}" x2="${n.x}" y2="${n.y}"/>`;})).join('')}</svg>${book.nodes.map(n=>`<button data-book-node="${n.art}" style="left:${n.x}%;top:${n.y}%" aria-pressed="false">${arts[n.art].name}<small>${sim.progression.learned[n.art]?'Known independently':'Locked'}</small></button>`).join('')}</div><div class="book-node-detail" aria-live="polite">Select a node to inspect its requirements.</div></article>`).join('')}</details>`;}
export function bindBookLibrary(root:HTMLElement,sim:CombatSimulation){root.querySelectorAll<HTMLButtonElement>('[data-book-node]').forEach(b=>b.onclick=()=>{
 const book=skillBooks.find(book=>book.nodes.some(n=>n.art===b.dataset.bookNode))!,node=book.nodes.find(n=>n.art===b.dataset.bookNode)!,req=bookRequirements(node,sim.progression);
 root.querySelectorAll('[data-book-node]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));
 const labels:Record<string,string>={hits:'basic hits',evades:'successful evades',parries:'perfect parries',breaks:'Breaks',kills:'victories'};
 b.closest('.book-preview')!.querySelector('.book-node-detail')!.innerHTML=`<h3>${arts[node.art].name}</h3><p>${sim.progression.learned[node.art]?'Already known through your current training.':'Not yet learned.'}</p><ul><li>Book ownership: unavailable until the future tutorial dungeon is implemented.</li>${req.parents.map(r=>`<li>${r.met?'✓':'○'} Learn ${arts[r.id].name}</li>`).join('')}${req.practice.map(r=>`<li>${r.met?'✓':'○'} ${r.current} / ${r.required} eligible ${labels[r.key]}</li>`).join('')}</ul><p>Preview only. This screen does not grant skills or replace the combat induction reward.</p>${skillCard(arts[node.art],sim)}`;
 });}
