import type {CombatSimulation} from '../combat/simulation';
import {bindingText,type Bindings} from '../input/bindings';
export class TrainingOrb {
 panel=document.createElement('section');prompt=document.createElement('button');
 constructor(private sim:CombatSimulation,private bindings:()=>Bindings,private guided:()=>void){this.panel.id='training-orb';this.panel.hidden=true;this.prompt.id='orb-prompt';this.prompt.hidden=true;document.getElementById('ui')!.append(this.panel,this.prompt);this.prompt.onclick=()=>this.open();}
 get available(){return Math.hypot(this.sim.player.x-2,this.sim.player.z+9)<2.4&&this.sim.free&&!this.sim.practiceMode&&!this.sim.encounter.active&&!this.sim.enemies.some(e=>e.hp>0)&&this.sim.player.hp>0;}
 close(){this.panel.hidden=true;}
 update(active:boolean){this.prompt.hidden=!active||!this.available||!this.panel.hidden;this.prompt.textContent=bindingText(this.bindings(),'interact')+' · Touch training orb';if(!active||!this.available)this.close();}
 open(){if(!this.available)return;this.panel.hidden=false;this.panel.innerHTML=`<div class="tray-heading"><h2>Training orb</h2><button id="orb-close" aria-label="Close training orb">×</button></div><p>Choose an opponent. Health and stamina are restored before each bout. Return here after victory to fight again.</p><button id="orb-guided"><b>Guild Combat Trial</b><span>Targeting, facing, dodge, counter, counterattack, Arts and Break.</span></button><button data-opponent="sentinel"><b>Aether Sentinel</b><span>Practice sword reads, counters and sweep dodges.</span></button><button data-opponent="boar"><b>Woodland Boar</b><span>Counter its tusk jab. Dodge the heavy head sweep.</span></button>`;this.panel.querySelector<HTMLButtonElement>('#orb-guided')!.onclick=()=>{if(this.available){this.close();this.guided();}};this.panel.querySelector<HTMLButtonElement>('#orb-close')!.onclick=()=>this.close();this.panel.querySelectorAll<HTMLButtonElement>('[data-opponent]').forEach(b=>b.onclick=()=>{if(!this.available)return;this.sim.reset();this.sim.spawnEnemy(b.dataset.opponent as 'sentinel'|'boar');this.sim.lockedId=this.sim.enemies[0].id;this.close();});}
}
