import {exitDoor,RegionTracker} from './regions';
import {publicUrl} from '../publicUrl';
import {buyPotion,claimChest,choosePrimer,primers,journalArts} from './journey';
import {cavernAreas,patrols,chestAreas,nearestArea,projectToCavern} from './cavern';
import type {CombatSimulation,CombatEvent} from '../combat/simulation';
import type {LabScene} from '../engine/scene';
import {DungeonView} from '../engine/dungeonView';
import {bindingText,type Bindings,type Action} from '../input/bindings';
import {arts} from '../data/arts';
import {supplies} from '../data/items';
export class Dungeon {
 private regions=new RegionTracker();private banner=document.createElement('aside');private bannerTime=0;private doorOpening=0;
 beforeLeaveTraining:()=>void=()=>{};
 world:DungeonView;panel=document.createElement('section');modal=document.createElement('section');dialog=document.createElement('section');prompt=document.createElement('button');dialogOpen=false;private invalid=false;private loaded=false;
 constructor(public sim:CombatSimulation,private view:LabScene,private bindings:()=>Bindings,private persist:()=>Promise<void>,private closeInput:()=>void){
  this.banner.id='region-banner';this.banner.hidden=true;this.banner.setAttribute('role','status');document.querySelector('#ui')!.append(this.banner);
  this.world=new DungeonView(view);this.panel.id='journey-objective';this.modal.id='journey-modal';this.dialog.id='journey-dialogue';this.prompt.id='journey-interact';this.modal.hidden=this.dialog.hidden=true;this.modal.setAttribute('role','dialog');this.dialog.setAttribute('role','dialog');this.prompt.onclick=()=>this.active?this.interact():this.leaveTraining();document.querySelector('#ui')!.append(this.panel,this.modal,this.dialog,this.prompt);
 }
 get atHallExit(){return !this.active&&Math.hypot(this.sim.player.x,this.sim.player.z+12.2)<2.4&&this.sim.free;}
 leaveTraining(){if(!this.atHallExit)return;this.beforeLeaveTraining();const j=this.sim.journey;j.active=true;j.position={x:0,z:168};j.checkpointHp=this.sim.hpMax;if(!j.facts.includes('exit-open'))j.facts.push('exit-open');this.enter(false);this.view.camera.alpha=Math.PI/2;void this.persist();}
 get active(){return this.sim.journey.active;}get room(){return cavernAreas[this.sim.journey.room];}get combat(){return this.active&&this.sim.enemies.some(e=>e.hp>0&&Math.hypot(e.x-this.sim.player.x,e.z-this.sim.player.z)<13);}
 async init(){const image=new Image();image.src=publicUrl('/assets/characters/mira_portrait.png');void image.decode().catch(()=>console.warn("Mira portrait preload unavailable; dialogue will retry the image."));await this.world.init();if(this.active)this.enter(false);else this.training();}
 private join(){const s=this.sim,j=s.journey;if(j.facts.includes('joined'))return;j.facts.push('joined');s.progression.learned['focused-strike']='starter';s.loadout=['focused-strike',null,null,null];void this.persist();}
 start(){if(this.sim.gmMode){this.sim.emit('notice','Exit GM mode before beginning the journey.');return;}this.sim.journey.active=true;this.enter(true);}
 training(){this.sim.journey.active=false;this.sim.suppressFieldProgression=false;this.join();this.sim.reset();this.hide();this.loaded=false;void this.persist();}
 private hide(){this.world.hide();this.banner.hidden=true;this.panel.hidden=this.prompt.hidden=this.modal.hidden=this.dialog.hidden=true;this.dialogOpen=false;document.getElementById('ui')!.classList.remove('journey-active');}
 enter(announce=true){
  const s=this.sim,j=s.journey;if(!j.facts.includes('awakened')&&announce){j.position={x:0,z:-6};j.checkpoint={...j.position};}this.closeInput();s.reset();s.suppressFieldProgression=true;Object.assign(s.player,projectToCavern(j.position));s.player.hp=Math.min(s.hpMax,j.checkpointHp);this.view.camera.alpha=-Math.PI/2;
  for(const group of patrols){const a=cavernAreas[group.area];for(let n=0;n<group.count;n++){const id=`cavern-${group.area}-${n}`;if(j.defeated.includes(id))continue;s.spawnEnemy(group.area===7?'captain':'goblin');const e=s.enemies.at(-1)!;e.id=id;e.x=a.x+(n?2:-2);e.z=a.z+3;e.hp=e.maxHp=group.hp;}}
  s.lockedId=null;this.loaded=true;this.invalid=false;this.regions=new RegionTracker();this.world.show();document.getElementById('ui')!.classList.add('journey-active');this.join();this.render();this.update([],0);if(announce)this.opening();void this.persist();
 }
 retry(){if(!this.active||this.sim.player.hp>0)return;const j=this.sim.journey;j.position={...j.checkpoint};j.checkpointHp=this.sim.hpMax;this.enter(false);}
 private k(a:Action){return bindingText(this.bindings(),a);}
 private render(){const j=this.sim.journey;this.panel.hidden=false;this.panel.innerHTML=`<small>${j.coins} Col</small><details><summary>${j.quest==='accepted'?'◇ Find an exit':j.quest==='completed'?'✓ Find an exit':'Personal journal'}</summary><p>${j.quest==='accepted'?'Reach the daylight beyond the goblin captain. Reward: a choice of one introductory Skill Book.':j.quest==='declined'?'No active quest. You are free to explore; no quest reward will be granted.':j.quest==='completed'?'Exit found. Your reward and completed quest are recorded.':'Your journey has begun.'}</p><p>Items, Skills, discovered places and contacts live in ${this.k('menu')} · Menu. Optional control bindings are in game settings.</p></details>`;}
 private message(title:string,body:string,next:()=>void=()=>{}){this.modal.hidden=false;this.modal.className='hologram-message';this.modal.innerHTML=`<article><h2>${title}</h2><div class="message-body"><p>${body}</p></div><button id="journey-confirm" aria-label="Dismiss message">Close</button></article>`;this.modal.querySelector<HTMLButtonElement>('button')!.onclick=()=>{this.modal.hidden=true;next();this.view.canvas.focus();};}
 private opening(){const j=this.sim.journey;if(!j.facts.includes('awakened')){this.narrate('Beneath the First Dawn',[
 'Cold stone presses against your back. Water drips somewhere in the dark. You wake in a cavern with a blade at your side and no memory of the path that brought you here.',
 'Far above, a bell sounds through the rock. A faint blue window gathers in the air beside you. Beyond its light, the cavern branches into darkness.'
 ],()=>{j.facts.push('awakened');void this.persist();this.welcome();});}else if(!j.facts.includes('message-read'))this.welcome();else if(j.quest==='offered')this.offerQuest();}
 private welcome(){const j=this.sim.journey;this.message('Message',`Welcome to the Game. Joining reward: Focused Strike, a Basic Art usable with your starting weapon. ${this.k('forward')} / ${this.k('left')} / ${this.k('backward')} / ${this.k('right')} move; move the mouse to look (click the scene to recapture; Esc releases the cursor). ${this.k('interact')} interacts with nearby objects. ${this.k('menu')} opens your personal menu. Your blade and the cavern are yours to discover.`,()=>{if(!j.facts.includes('message-read'))j.facts.push('message-read');void this.persist();if(j.quest==='offered')this.offerQuest();});}
 private offerQuest(){this.modal.hidden=false;this.modal.className='hologram-alert';this.modal.innerHTML=`<article><h2>Alert</h2><div class="message-body"><h3>Find an exit</h3><p>Find a route to the town above. Defeat the goblin captain guarding the daylight stair.</p><p><b>Completion reward:</b> choose one small, weapon-neutral Skill Book.</p><small>Declining leaves you free to explore, but grants no official quest or quest reward.</small></div><div class="alert-actions"><button id="accept-exit-quest" class="accept" aria-label="Accept Find an exit quest">○</button><button id="decline-exit-quest" class="decline" aria-label="Decline quest and reward">×</button></div></article>`;
  for(const [id,value] of [['accept-exit-quest','accepted'],['decline-exit-quest','declined']] as const)this.modal.querySelector<HTMLButtonElement>('#'+id)!.onclick=()=>{this.sim.journey.quest=value;this.modal.hidden=true;this.regions=new RegionTracker();this.render();void this.persist();this.view.canvas.focus();};}
 private narrate(name:string,lines:string[],done:()=>void,portrait=false){let index=0;if(portrait)this.world.npc.setEnabled(false);this.closeInput();this.dialogOpen=true;this.modal.hidden=true;this.dialog.hidden=false;const draw=()=>{this.dialog.innerHTML=`${portrait?`<img src="${publicUrl('/assets/characters/mira_portrait.png')}" alt="Mira Vale, town wayfinder">`:''}<article class="${portrait?'':'narration'}"><small>${portrait?'TOWN WAYFINDER':'PROLOGUE'}</small><h2>${name}</h2><p>${lines[index]}</p><span>${index+1} / ${lines.length}</span><button id="dialogue-next">Continue</button></article>`;this.dialog.querySelector<HTMLButtonElement>('button')!.onclick=()=>{if(++index<lines.length)draw();else{this.dialog.hidden=true;this.dialogOpen=false;if(portrait)this.world.npc.setEnabled(true);done();this.view.canvas.focus();}};};draw();}
 update(events:CombatEvent[],dt:number){
  if(!this.active){this.prompt.hidden=!this.atHallExit;this.prompt.textContent=this.atHallExit?`${this.k('interact')} · Exit to Town Square`:'';document.querySelector('.location')!.innerHTML='<i></i>Training Room<small>TOWN OF BEGINNINGS · GUILD HALL</small>';return;}if(!this.loaded)return;const s=this.sim,j=s.journey;if(!s.rewardEligible)this.invalid=true;if(!this.dialogOpen&&s.player.hp>0)j.elapsedMs+=Math.max(0,Math.min(100,dt));
  j.position={x:s.player.x,z:s.player.z};const nearest=nearestArea(s.player.x,s.player.z),area=nearest===9&&s.player.z<148?8:nearest;if(!j.visited.includes(area))j.visited.push(area);if(j.room!==area){j.room=area;this.render();}
  document.querySelector('.location')!.innerHTML=`<i></i>${this.room.name}<small>${area===9?'FLOOR 1':'BENEATH THE TOWN OF BEGINNINGS'}</small>`;
  if(s.rewardEligible&&!this.invalid){let changed=false;for(const e of s.enemies)if(e.hp<=0&&!j.defeated.includes(e.id)){j.defeated.push(e.id);changed=true;if(e.species==='captain'&&!j.facts.includes('boss'))j.facts.push('boss');}
   if(changed){j.cleared=patrols.filter(g=>Array.from({length:g.count},(_,n)=>`cavern-${g.area}-${n}`).every(id=>j.defeated.includes(id))).map(g=>g.area);void this.persist();}}
  if(this.doorOpening>0){this.doorOpening-=dt;if(this.doorOpening<=0){j.facts.push('exit-open');void this.persist();}}
  const entered=this.regions.update(s.player);if(entered!==null){this.banner.innerHTML=`<small>${entered===9?'FLOOR 1 · SAFE HAVEN':'UNDER-TOWN CAVERNS'}</small><strong>${entered===9?'Town of Beginnings':'Under-town Caverns'}</strong><span>◇ ━━━━━━━━━ ◇</span>`;this.banner.hidden=false;this.banner.style.animation='none';void this.banner.offsetWidth;this.banner.style.animation='';this.bannerTime=5200;}else if(this.bannerTime>0){this.bannerTime-=dt;if(this.bannerTime<=0)this.banner.hidden=true;}
  this.world.update(s.player,j.room,j.looted,j.facts.includes('boss'),j.facts.includes('exit-open')||this.doorOpening>0,dt);const near=this.near();this.prompt.hidden=!near||this.dialogOpen||s.player.hp<=0;this.prompt.textContent=near?`${this.k('interact')} · ${near.label}`:'';
  this.panel.querySelector('small')!.textContent=j.coins+' Col';
 }
 private near(){if(this.combat||!this.sim.free)return null;const s=this.sim,j=s.journey;const objects=[...(!j.facts.includes('exit-open')&&this.doorOpening<=0?[{id:'exit-door',label:'Open stone door',x:exitDoor.x-.8,z:exitDoor.z-1}]:[]),{id:'guild-hall',label:'Enter Guild Hall · Training Room',x:0,z:170},...chestAreas.filter(i=>!j.looted.includes('chest-'+i)).map(i=>({id:'chest-'+i,label:'Examine chest',x:cavernAreas[i].x-5,z:cavernAreas[i].z+3})),...[[0,4,-4],[3,-26,26],[6,-26,56]].map(([i,x,z])=>({id:'rest-'+i,label:'Rest at the lantern',x,z})),{id:'supply',label:'Examine provision cache',x:-33,z:27},{id:'mira',label:'Speak with Mira',x:0,z:161}];return objects.filter(o=>Math.hypot(o.x-s.player.x,o.z-s.player.z)<2.4).sort((a,b)=>Math.hypot(a.x-s.player.x,a.z-s.player.z)-Math.hypot(b.x-s.player.x,b.z-s.player.z))[0]??null;}
 interact(){if(!this.active||this.dialogOpen)return;const s=this.sim,j=s.journey,o=this.near();if(!o)return;if(this.invalid||!s.rewardEligible){s.emit('notice','Debug changes disable rewards until a clean checkpoint reload.');return;}
  if(o.id==='exit-door'){if(j.facts.includes('boss')){this.doorOpening=1000;s.emit('notice','The stone door rises. Daylight spills into the passage.');}return;}
  if(o.id==='guild-hall'){this.training();return;}
  if(o.id.startsWith('chest-')){if(claimChest(j,o.id,30)){s.profile.potions.health=Math.min(99,s.profile.potions.health+1);s.emit('notice','Treasure · 30 Col · Health potion');void this.persist();}}
  if(o.id.startsWith('rest-')){s.player.hp=s.hpMax;s.player.stamina=s.staminaMax;j.checkpoint={x:s.player.x,z:s.player.z};j.checkpointHp=s.hpMax;s.emit('notice','Rested · checkpoint saved');void this.persist();}
  if(o.id==='supply')this.shop();if(o.id==='mira')this.conversation();
 }
 private shop(){this.modal.hidden=false;this.modal.className='hologram-message';this.modal.innerHTML=`<article><h2>Provision cache</h2><div class="message-body"><p>A weathered notice: “Leave 20 Col for each bottle.”</p><p>${this.sim.journey.coins} Col · Health potion restores ${supplies.health.restore} HP outside combat.</p></div><button id="buy-potion">Buy · 20 Col</button><button id="journey-confirm">Leave</button></article>`;this.modal.querySelector<HTMLButtonElement>('#buy-potion')!.onclick=()=>{if(this.sim.profile.potions.health>=99)return;if(buyPotion(this.sim.journey)){this.sim.profile.potions.health++;void this.persist();this.shop();}else this.sim.emit('notice','Not enough Col');};this.modal.querySelector<HTMLButtonElement>('#journey-confirm')!.onclick=()=>this.modal.hidden=true;}
 private completeQuest(){const j=this.sim.journey;if(j.quest==='accepted'&&j.facts.includes('boss')){j.quest='completed';void this.persist();this.chooseBook();}else if(j.quest==='completed'&&!j.book)this.chooseBook();else this.message('Message','Welcome to the Town of Beginnings. Mira is now a contact. The under-town route is clear.');this.render();}
 private chooseBook(){this.modal.hidden=false;this.modal.className='book-reward';this.modal.innerHTML=`<article class="book-choice"><small>QUEST COMPLETE · FIND AN EXIT</small><h2>Choose your Skill Book</h2><p>One modest Basic Art now; a second node earned through later practice. All weapons and characters can use these forms.</p><div class="primer-options">${primers.map(b=>`<section><h3>${b.name}</h3><p>${b.theme}</p><details><summary>${arts[b.root].name} · ${arts[b.root].cost} SP</summary><p>${arts[b.root].description} ${arts[b.root].nodes[0].multiplier}× weapon base damage; ${arts[b.root].nodes[0].break} Break. Hold 600 ms. Perfect ±55 ms; Good ±120 ms.</p><p>${b.requirement}</p></details><button data-primer="${b.id}">Choose</button></section>`).join('')}</div></article>`;
  this.modal.querySelectorAll<HTMLButtonElement>('[data-primer]').forEach(b=>b.onclick=()=>{const book=primers.find(p=>p.id===b.dataset.primer)!;this.message('Confirm '+book.name,book.theme,()=>{});this.modal.querySelector('#journey-confirm')!.textContent='Compare again';(this.modal.querySelector('#journey-confirm') as HTMLButtonElement).onclick=()=>this.chooseBook();const accept=document.createElement('button');accept.textContent='Accept book';accept.id='accept-book';accept.onclick=()=>{if(choosePrimer(this.sim.journey,book.id)){for(const id of journalArts(this.sim.journey))this.sim.progression.learned[id]='skill book';const slot=this.sim.loadout.indexOf(null);if(slot>=0)this.sim.loadout[slot]=book.root;void this.persist();this.message('Skill Book received',`${book.name} · ${arts[book.root].name} learned. Review and equip your skills in the personal menu.`);}};this.modal.querySelector('article')!.append(accept);});
 }
 private conversation(){const j=this.sim.journey;this.narrate('Mira Vale',[
 'You made it! I’m Mira Vale, the town’s wayfinder. Thank you, all of you—your party cleared the goblins from the old caverns before they reached our streets.',
 'They came through a drain beyond the outer wall. Those gates were sealed. Either the goblins found another way in… or someone opened one for them.',
 'A crown and three spears on their captain’s token. That is no wandering scavenger’s mark. Beyond the animals near our gates, something organized is gathering outside the Town of Beginnings.',
 'Welcome home, for now. Rest and get your bearings. Ilyra can teach formal combat in the Guild Hall, including the Linear technique. You are free to learn in your own way.',
 'Bring that token to the eastern watch when you are ready. Your story is only beginning.'
 ],()=>{for(const fact of ['mira','town-quest'])if(!j.facts.includes(fact))j.facts.push(fact);void this.persist();this.completeQuest();},true);}
}
